#!/usr/bin/env python3

import dbus

if __name__ == '__main__':
	bus = dbus.SystemBus()
	udisks = bus.get_object('org.freedesktop.UDisks2', '/org/freedesktop/UDisks2/Manager')
	paths = udisks.GetBlockDevices([], dbus_interface='org.freedesktop.UDisks2.Manager')
	data = []

	for path in paths:
		block = bus.get_object('org.freedesktop.UDisks2', path)
		properties1 = block.GetAll('org.freedesktop.UDisks2.Block', dbus_interface='org.freedesktop.DBus.Properties')
		device = str(bytes(properties1['Device']).strip(b'\x00'), 'utf-8')
		usage = str(properties1['IdUsage'])
		type = str(properties1['IdType'])
		name = str(properties1['HintName'])
		system = bool(properties1['HintSystem'])
		ignore = bool(properties1['HintIgnore'])
		options = str(properties1['UserspaceMountOptions'])
		if usage == 'filesystem' and ignore == False and options.find('x-gdu.hide') == -1:
			properties2 = block.GetAll('org.freedesktop.UDisks2.Filesystem', dbus_interface='org.freedesktop.DBus.Properties')
			for mount in properties2['MountPoints']:
				root = str(bytes(mount).strip(b'\x00'), 'utf-8')
				data.append((root, device, type, name, system, ignore))

	for item in sorted(data, key=lambda x: x[0]):
		if item[3] != "":
			print("%s:${alignr}${fs_used_perc %s}%% ${fs_bar 5,172 %s}" % (item[3], item[0], item[0]))
		else:
			print("%s:${alignr}${fs_used_perc %s}%% ${fs_bar 5,172 %s}" % (item[0], item[0], item[0]))

