#!/usr/bin/env python3

import sys
import re

if __name__ == "__main__":
	model = None

	if len(sys.argv) > 1:
		model = ' '.join(sys.argv[1:])
	else:
		with open('/proc/cpuinfo') as cpuinfo:
			for line in cpuinfo:
				if line.startswith('model name'):
					model = line[13:]

	model = re.sub('\s*@\s+\d+(\.\d+)?\s*GHz$', '', model, 1, re.I)
	model = re.sub('[A-Za-z0-9]+-Core Processor', '', model, 1)
	model = re.sub(' APU with Radeon\(tm\) HD Graphics$', '', model, 1, re.I)
	model = re.sub(' APU with Radeon HD Graphics$', '', model, 1, re.I)
	model = re.sub(' APU with AMD Radeon R\d+ Graphics$', '', model, 1, re.I)
	model = re.sub(' RADEON R\d+, \d+ COMPUTE CORES \d+C\+\d+G$', '', model, 1, re.I)
	model = re.sub(' R\d+, \d+ COMPUTE CORES \d+C\+\d+G$', '', model, 1, re.I)
	model = re.sub('\((r|tm|R|TM)\)', '', model, 0, re.I)
	model = re.sub('^[A-Za-z0-9]+-Core\s+', '', model, 1, re.I)
	model = re.sub('\s+[A-Za-z0-9]+-Core$', '', model, 1, re.I)
	model = re.sub('\s+[A-Za-z0-9]+-Core\s+', ' ', model, 0, re.I)
	model = re.sub('\s+Processor$', '', model, 1, re.I)
	model = re.sub('\s+Processor\s+', ' ', model, 0, re.I)
	model = re.sub('\s+CPU$', '', model, 1, re.I)
	model = re.sub('\s+CPU\s+', ' ', model, 0, re.I)
	model = model.strip()

	print(model)

