

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Conky Settings to Account"
      when: "account_server_enabled|default(false)"
      block:
 
        - name: "Applying Server Settings to Account: Copying Configuration Files"
          template:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: "bin/geeqie-remote", mode: "0755" }
            - { path: "bin/mount-server", mode: "0755" }
            - { path: "bin/mount-torrents", mode: "0755" }


