

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Bash Settings to Account"
      when: "account_bash_enabled|default(false)"
      block:

        - name: "Applying Bash Settings to Account: Create Required Directory"
          file:
            path: "/home/kmchan/.profile.d"
            state: "directory"
            owner: "kmchan"
            group: "kmchan"
            mode: "0755"

        - name: "Applying Bash Settings to Account: Update Profile Script"
          blockinfile:
            path: "/home/kmchan/.profile"
            state: "present"
            marker: "# {mark} include files from ~/.profile.d/"
            block: |-
              if [ -d ~/.profile.d ]; then
                  for i in ~/.profile.d/*.sh; do
                      if [ -r $i ]; then
                          . $i
                      fi
                  done
                  unset i
              fi


