

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Firefox Settings to Account"
      when: "account_firefox_enabled|default(false)"
      block:

        - name: "Applying Firefox Settings to Account: Copying Configuration Files"
          copy:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: ".config/firejail/firefox-alternative.profile", mode: "0644" }
            - { path: ".config/firejail/firefox-default.profile", mode: "0644" }
            - { path: ".config/firejail/firefox-private.profile", mode: "0644" }
            - { path: ".config/firejail/firefox-test.profile", mode: "0644" }
            - { path: ".config/firejail/firefox-work.profile", mode: "0644" }
            - { path: ".config/firejail/firefox.inc", mode: "0644" }
            - { path: ".local/share/applications/firefox-esr.desktop", mode: "0644" }
            - { path: ".local/share/applications/firefox.desktop", mode: "0644" }

        - name: "Applying Firefox Settings to Account: Writing Configuration Files"
          template:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: ".local/share/applications/firefox-alternative.desktop", mode: "0644" }
            - { path: ".local/share/applications/firefox-default.desktop", mode: "0644" }
            - { path: ".local/share/applications/firefox-private.desktop", mode: "0644" }
            - { path: ".local/share/applications/firefox-test.desktop", mode: "0644" }
            - { path: ".local/share/applications/firefox-work.desktop", mode: "0644" }


