

- hosts: "all"
  become: true
  become_user: "kmchan"

  vars:

    account_conky_fontawesome_version: "master"
    account_conky_fontawesome_url: "https://github.com/FortAwesome/Font-Awesome"
    account_conky_fontawesome_directory: "/home/kmchan/.config/conky/fontawesome"

  tasks:

    - name: "Applying Conky Settings to Account"
      when: "account_conky_enabled|default(false)"
      block:

        - name: "Applying Conky Settings to Account: Copying Configuration Files"
          copy:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: "bin/udisks2temp", mode: "0755" }
            - { path: ".config/autostart/conky.desktop", mode: "0644" }
            - { path: ".config/conky/conky.conf", mode: "0644" }
            - { path: ".config/conky/processor", mode: "0755" }
            - { path: ".config/conky/filesystems", mode: "0755" }
            - { path: ".config/conky/sensors", mode: "0755" }
            - { path: ".config/conky/weather", mode: "0755" }
            - { path: ".config/conky/database.json", mode: "0644" }
            - { path: ".config/systemd/user/udisks2temp.service", mode: "0644" }

        - name: "Applying Conky Settings to Account: Checkout Font Awesome Icon Library"
          git:
            dest: "{{ account_conky_fontawesome_directory }}"
            repo: "{{ account_conky_fontawesome_url }}"
            version: "{{ account_conky_fontawesome_version }}"
            clone: "yes"
            update: "yes"
            remote: "origin"
            accept_hostkey: "yes"


