

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Bumblebee Settings to Account"
      when: "account_bumblebee_enabled|default(false)"
      block:

        - name: "Applying Bumblebee Settings to Account: Add User to Bumblebee Group"
          user:
            name: "kmchan"
            state: "present"
            groups: "bumblebee"
            append: "yes"

        - name: "Applying Bumblebee Settings to Account: Install Socket Proxy"
          copy:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: ".config/systemd/user/bumblebee-proxy.socket", mode: "0644" }
            - { path: ".config/systemd/user/bumblebee-proxy.service", mode: "0644" }


