

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Steam Settings to Account"
      when: "account_steam_enabled|default(false)"
      block:

        - name: "Applying Steam Settings to Account: Install Desktop File"
          firejail_xdg_desktop_file:
            dest: "/home/kmchan/.local/share/applications/steam.desktop"
            src: "/usr/share/applications/steam.desktop"
            parameters: "--profile=steam"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"

        - name: "Applying Steam Settings to Account: Extract User Information"
          getent:
            database: "passwd"
            key: "kmchan"
            split: ":"
          when: "service_bumblebee_enabled|default(false)"

        - name: "Applying Steam Settings to Account: Determine Bumblebee Proxy Socket Location"
          set_fact:
            bumblebee_socket: "/run/user/{{ ansible_facts.getent_passwd['kmchan'][1] }}/bumblebee"
          when: "service_bumblebee_enabled|default(false)"

        - name: "Applying Steam Settings to Account: Install Local Firejail Customizations"
          template:
            dest: "/home/kmchan/.config/firejail/steam.profile"
            src: "{{ playbook_dir }}/files/home/kmchan/.config/firejail/steam.profile.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"
    

