

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Applying Docker Settings to Account"
      when: "account_docker_enabled|default(false)"
      block:

        - name: "Applying Docker Settings to Account: Add User to Docker Group"
          user:
            name: "kmchan"
            state: "present"
            groups: "docker"
            append: "yes"


