

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying qBittorrent Settings to Account"
      when: "account_qbittorrent_enabled|default(false)"
      block:

        - name: "Applying qBittorrent Settings to Account: Install Desktop File"
          firejail_xdg_desktop_file:
            dest: "/home/kmchan/.local/share/applications/org.qbittorrent.qBittorrent.desktop"
            src: "/usr/share/applications/org.qbittorrent.qBittorrent.desktop"
            parameters: "--profile=qbittorrent"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"

        - name: "Applying qBittorrent Settings to Account: Install Local Firejail Customizations"
          template:
            dest: "/home/kmchan/.config/firejail/qbittorrent.profile"
            src: "{{ playbook_dir }}/files/home/kmchan/.config/firejail/qbittorrent.profile.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"


