

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Firefox Settings to Account"
      when: "account_firefox_enabled|default(false)"
      block:

        - name: "Applying Firefox Settings to Account: Hide System Desktop Files"
          template:
            dest: "{{ item.path }}"
            src: "{{ playbook_dir }}/files/{{ item.path }}"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"
          loop:
            - { path: "/home/kmchan/.local/share/applications/firefox.desktop" }
            - { path: "/home/kmchan/.local/share/applications/firefox-esr.desktop" }

        - name: "Applying Firefox Settings to Account: Install Custom Desktop Files"
          template:
            dest: "/home/kmchan/.local/share/applications/firefox-{{ profile.name }}.desktop"
            src: "{{ playbook_dir }}/files/home/kmchan/.local/share/applications/firefox-profile.desktop.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"
          loop: "{{ account_firefox_profiles|default([]) }}"
          loop_control:
            loop_var: "profile"

        - name: "Applying Firefox Settings to Account: Install Custom Firejail Profiles"
          template:
            dest: "/home/kmchan/.config/firejail/firefox-{{ profile.name }}.profile"
            src: "{{ playbook_dir }}/files/home/kmchan/.config/firejail/firefox-profile.profile.j2"
            owner: "kmchan"
            group: "kmchan"
            mode: "0644"
          loop: "{{ account_firefox_profiles|default([]) }}"
          loop_control:
            loop_var: "profile"


