

- hosts: "all"
  become: true
  become_user: "kmchan"

  tasks:

    - name: "Applying Skype Settings to Account"
      when: "account_skype_enabled|default(false)"
      block:

        - name: "Applying Skype Settings to Account: Copying Configuration Files"
          copy:
            dest: "/home/kmchan/{{ item.path }}"
            src: "{{ playbook_dir }}/files/home/kmchan/{{ item.path }}"
            owner: "kmchan"
            group: "kmchan"
            mode: "{{ item.mode }}"
          loop:
            - { path: ".local/share/applications/skypeforlinux.desktop", mode: "0644" }


