

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    hardware_kvm_ignore_msrs: true
    hardware_kvm_amd_avic: true
    hardware_kvm_amd_npt: true

  tasks:

    - name: "Configure Kernel-Based Virtual Machine: Enable Kernel Modules at Boot"
      ansible.builtin.template:
        dest: "/etc/modules-load.d/kvm.conf"
        src: "{{ playbook_dir }}/files/desktop/etc/modules-load.d/kvm.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configure Kernel-Based Virtual Machine: Update Kernel Module Parameters"
      ansible.builtin.template:
        dest: "/etc/modprobe.d/kvm.conf"
        src: "{{ playbook_dir }}/files/desktop/etc/modprobe.d/kvm.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"


