

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    hardware_vfio_disable_nvidia_pat: true

  tasks:

    - name: "Configure Virtual Function IO: Enable Kernel Modules at Boot"
      ansible.builtin.copy:
        dest: "/etc/modules-load.d/vfio.conf"
        src: "{{ playbook_dir }}/files/desktop/etc/modules-load.d/vfio.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configure Virtual Function IO: Configure Kernel Module Options"
      ansible.builtin.template:
        dest: "/etc/modprobe.d/vfio.conf"
        src: "{{ playbook_dir }}/files/desktop/etc/modprobe.d/vfio.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configure Virtual Function IO: Enable IOMMU Support in Kernel Command Line"
      ansible.builtin.shell:
        cmd: "grubby --update-kernel=ALL --args=iommu=pt"

    - name: "Configure Virtual Function IO: Enable Intel IOMMU Support in Kernel Command Line"
      ansible.builtin.shell:
        cmd: "grubby --update-kernel=ALL --args=intel_iommu=on"
      when: "'GenuineIntel' in ansible_processor"

    - name: "Configure Virtual Function IO: Enable AMD IOMMU Support in Kernel Command Line"
      ansible.builtin.shell:
        cmd: "grubby --update-kernel=ALL --args=amd_iommu=on"
      when: "'AuthenticAMD' in ansible_processor"

    - name: "Configure Virtual Function IO: Enable ACS Override in Kernel Command Line"
      ansible.builtin.shell:
        cmd: "grubby --update-kernel=ALL --args=pcie_acs_override={{ hardware_vfio_acs_override }}"
      when: "hardware_vfio_acs_override|default('') != ''"


