

- hosts: "desktop"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Disk Support: Install Tools from Distribution"
      ansible.builtin.dnf:
        name:
          - "nvme-cli"
          - "smartmontools"
        state: "latest"


