

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    software_packaging_enabled: true

  tasks:

    - name: "Setup RPM Development Tools"
      when: "software_packaging_enabled|default(false)"
      block:

        - name: "Setup RPM Development Tools: Install Tools from Distribution"
          ansible.builtin.dnf:
            name:
              - "createrepo_c"
              - "mock"
              - "redhat-rpm-config"
              - "rpm-build"
              - "rpmdevtools"
              - "rpmlint"
            state: "latest"


