

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    service_certbot_enabled: true

  tasks:

    - name: "Setup Certbot Service"
      when: "service_certbot_enabled|default(false)"
      block:

        - name: "Setup Certbot Service: Install Certbot Package"
          ansible.builtin.dnf:
            name: "certbot"
            state: "latest"

        - name: "Setup Certbot Service: Update Webroot Path in Default Configuration Files"
          ansible.builtin.lineinfile:
            path: "/etc/letsencrypt/cli.ini"
            line: "webroot-path = /var/www/certbot"
            regexp: "^\\s*#*\\s*webroot-path\\s*=\\s*.*$"
            state: "present"

        - name: "Setup Certbot Service: Create Extra Configuration Directories"
          ansible.builtin.file:
            dest: "{{ item.path }}"
            state: "directory"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0755') }}"
          loop:
            - { path: "/var/www/certbot/.well-known/acme-challenge" }

        - name: "Setup Certbot Service: Install Extra Configuration Files"
          ansible.builtin.template:
            dest: "{{ item.path }}"
            src: "{{ playbook_dir }}/files/desktop/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0644') }}"
          loop:
            - { path: "/etc/httpd/conf.d/certbot.conf" }

        - name: "Setup Certbot Service: Enable Certbot Service"
          ansible.builtin.systemd_service:
            name: "certbot-renew.timer"
            enabled: true
            daemon_reload: true


