

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    software_firefox_enabled: true

  tasks:

    - name: "Setup Firefox Browser"
      when: "software_firefox_enabled|default(false)"
      block:

        - name: "Setup Firefox Browser: Install Firefox from Distribution"
          ansible.builtin.dnf:
            name:
              - "firefox"
              - "firefox-langpacks"
            state: "latest"


