

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_steam_enabled: true
    software_steam_directories: [ "/mnt/games" ]

  tasks:

    - name: "Setup Steam"
      when: "software_steam_enabled|default(false)"
      block:

        - name: "Setup Steam: Create Application Specific Directories for Home Directory Template"
          ansible.builtin.file:
            path: "/etc/skel/{{ item }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"
          loop:
            - "Music/Steam"
            - "Pictures/Steam"

        - name: "Setup Steam: Install Steam from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/com.valvesoftware.Steam.flatpakref"
            state: "present"

        - name: "Setup Steam: Install Protontricks from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/com.github.Matoking.protontricks.flatpakref"
            state: "present"

        - name: "Setup Steam: Install Steam Device Udev Ruleset from Distribution"
          ansible.builtin.dnf:
            name: "steam-devices"
            state: "latest"

        - name: "Setup Steam: Enable Access to Offload Scripts"
          ansible.builtin.shell:
            cmd: "flatpak override --filesystem /opt/video:ro com.valvesoftware.Steam"

        - name: "Setup Steam: Enable Access to Application Specific Directories under Home"
          ansible.builtin.shell:
            cmd: "flatpak override --nofilesystem xdg-pictures --nofilesystem xdg-music --filesystem xdg-pictures/Steam --filesystem xdg-music/Steam com.valvesoftware.Steam"

        - name: "Setup Steam: Enable Access to Secondary Game Directories"
          ansible.builtin.shell:
            cmd: "flatpak override --filesystem {{ item }} com.valvesoftware.Steam"
          loop: "{{ software_steam_directories|default([]) }}"

        - name: "Setup Steam: Enable Access to Secondary Game Directories for Protontricks"
          ansible.builtin.shell:
            cmd: "flatpak override --filesystem {{ item }} com.github.Matoking.protontricks"
          loop: "{{ software_steam_directories|default([]) }}"


