

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_chromium_enabled: true

  tasks:

    - name: "Setup Chromium Browser"
      when: "software_chromium_enabled|default(false)"
      block:

        - name: "Setup Chromium Browser: Install Chromium from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/org.chromium.Chromium.flatpakref"
            state: "present"


