

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    software_golang_enabled: true

  tasks:

    - name: "Setup Go Development Tools"
      when: "software_golang_enabled|default(false)"
      block:

        - name: "Setup Go Development Tools: Install Go from Distribution"
          ansible.builtin.dnf:
            name: "golang"
            state: "latest"


