

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    service_ddclient_enabled: true

    service_ddclient_hosts:
      - { provider: "namecheap", domain: "kmchan3.space", host: "demo" }
      - { provider: "namecheap", domain: "kmchan3.space", host: "desktop" }
      - { provider: "namecheap", domain: "kmchan3.space", host: "firefox" }
      - { provider: "namecheap", domain: "kmchan3.space", host: "test" }

  tasks:

    - name: "Setup DDClient Service"
      when: "service_ddclient_enabled|default(false)"
      block:

        - name: "Setup DDClient Service: Load Namecheap Secrets"
          ansible.builtin.include_vars:
            file: "secrets/service.ddclient.vault"

        - name: "Setup DDClient Service: Install DDClient Package"
          ansible.builtin.dnf:
            name: "ddclient"
            state: "latest"

        - name: "Setup DDClient Service: Update Default Configuration Files"
          ansible.builtin.blockinfile:
            dest: "/etc/ddclient.conf"
            block: "{{ lookup('ansible.builtin.template', '{{ playbook_dir }}/files/etc/ddclient.conf.j2') }}"
            owner: "ddclient"
            group: "ddclient"
            mode: "0600"

        - name: "Setup DDClient Service: Enable DDClient Daemon"
          ansible.builtin.systemd_service:
            name: "ddclient.service"
            enabled: true
            daemon-reload: true


