

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    service_php_fpm_enabled: true

    service_php_fpm_users:
      - name: "kmchan"

  tasks:

    - name: "Setup PHP FPM Service"
      when: "service_php_fpm_enabled|default(false)"
      block:

        - name: "Setup PHP FPM Service: Fetch account group information"
          ansible.builtin.getent:
            database: "passwd"

        - name: "Setup PHP FPM Service: Install PHP FPM from Distribution"
          ansible.builtin.dnf:
            name: "php-fpm"
            state: "latest"

        - name: "Setup PHP FPM Service: Backup Default Configuration Files"
          ansible.builtin.shell:
            cmd: "cp -a {{ item.path }} {{ item.path }}.original"
            creates: "{{ item.path }}.original"
          loop:
            - { path: "/etc/httpd/conf.d/php.conf" }

        - name: "Setup PHP FPM Service: Create Custom Configuration Directories"
          ansible.builtin.file:
            dest: "{{ item.path }}"
            state: "directory"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0755') }}"
          loop:
            - { path: "/etc/systemd/system/php-fpm.service.d" }

        - name: "Setup PHP FPM Service: Install Custom Configuration Files"
          ansible.builtin.template:
            dest: "{{ item.path }}"
            src: "{{ playbook_dir }}/files/desktop/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0644') }}"
          loop:
            - { path: "/etc/httpd/conf.d/php.conf" }
            - { path: "/etc/php-fpm.d/users.conf" }
            - { path: "/etc/systemd/system/php-fpm.service.d/local.conf" }

        - name: "Setup PHP FPM Service: Create Root Backend Directory"
          ansible.builtin.file:
            dest: "/var/www/backend"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Setup PHP FPM Service: Create User Backend Directories"
          ansible.builtin.file:
            dest: "/var/www/backend/{{ item.name }}"
            state: "directory"
            owner: "{{ item.name|mandatory }}"
            group: "{{ getent_passwd[item.name|mandatory][2] }}"
            mode: "0755"
          loop: "{{ service_php_fpm_users|default([]) }}"

        - name: "Setup PHP FPM Service: Create User Runtime State Directories"
          ansible.builtin.file:
            dest: "/var/lib/php/{{ item.0.name|mandatory }}/{{ item.1 }}"
            state: "directory"
            owner: "{{ item.0.name|mandatory }}"
            group: "{{ getent_passwd[item.0.name|mandatory][2] }}"
            mode: "0770"
          loop: "{{ service_php_fpm_users|default([])|product(['', 'session', 'wsdlcache' ]) }}"

        - name: "Setup PHP FPM Service: Enable PHP FPM Daemon"
          ansible.builtin.systemd_service:
            name: "php-fpm.service"
            enabled: true
            daemon-reload: true


