

- import_playbook: "desktop.system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_console_enabled: true

  tasks:

    - name: "Setup Console Software"
      when: "software_console_enabled|default(false)"
      block:

        - name: "Setup Console Software: Install Console Software from Distribution"
          ansible.builtin.dnf:
            name:
              - "bchunk"
              - "bsdtar"
              - "cabextract"
              - "ccd2iso"
              - "convmv"
              - "curl"
              - "daa2iso"
              - "ffmpeg"
              - "git"
              - "glances"
              - "htop"
              - "innoextract"
              - "inxi"
              - "jdupes"
              - "jq"
              - "lshw"
              - "mc"
              - "neofetch"
              - "nrg2iso"
              - "nvtop"
              - "openssh"
              - "p7zip"
              - "p7zip-plugins"
              - "ripgrep"
              - "rsync"
              - "screen"
              - "socat"
              - "sqlite"
              - "sshfs"
              - "telnet"
              - "tldr"
              - "tmux"
              - "unace"
              - "unrar"
              - "unrar-free"
              - "vim"
              - "yt-dlp"
            state: "latest"


