

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_golang_enabled: true

    software_golang_packages:
      - "golang"

  tasks:

    - name: "Setup Go Development Tools"
      when: "software_golang_enabled|default(false)"
      block:

        - name: "Setup Go Development Tools: Install Go from Distribution"
          ansible.builtin.dnf:
            name: "{{ software_golang_packages }}"
            state: "latest"


