

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    network_mounts:
      - path: /mnt/server/kmchan01
        remote: "192.168.254.1:/mnt/data/kmchan01"
        options: "nfsvers=4.2,rsize=131072,wsize=131072,noatime,nodiratime"
        type: "nfs4"
        on_boot: false
        force_unmount: true
        mount_timeout: 30
        idle_timeout: 600
      - path: /mnt/server/kmchan02
        remote: "192.168.254.1:/mnt/data/kmchan02"
        options: "nfsvers=4.2,rsize=131072,wsize=131072,noatime,nodiratime"
        type: "nfs4"
        on_boot: false
        force_unmount: true
        mount_timeout: 30
        idle_timeout: 600
      - path: /mnt/server/kmchan03
        remote: "192.168.254.1:/mnt/data/kmchan03"
        options: "nfsvers=4.2,rsize=131072,wsize=131072,noatime,nodiratime"
        type: "nfs4"
        on_boot: false
        force_unmount: true
        mount_timeout: 30
        idle_timeout: 600
      - path: /mnt/server/kmchan05
        remote: "192.168.254.1:/mnt/data/kmchan05"
        options: "nfsvers=4.2,rsize=131072,wsize=131072,noatime,nodiratime"
        type: "nfs4"
        on_boot: false
        force_unmount: true
        mount_timeout: 30
        idle_timeout: 600

  tasks:

    - name: "Setup Network Mounts: Install Helper Tools from Distribution"
      ansible.builtin.dnf:
        name:
          - "cifs-utils"
          - "nfs-utils"
        state: "latest"

    - name: "Setup Network Mounts: Install Systemd Mount Unit for Mount Points"
      ansible.builtin.template:
        dest: "/etc/systemd/system/{{ item.path|replace('/', '-')|regex_replace('^-') }}.mount"
        src: "{{ playbook_dir }}/files/etc/systemd/system/network.mounts.mount.j2"
        owner: "root"
        group: "root"
        mode: "0644"
      vars:
        path: "{{ item.path }}"
        remote: "{{ item.remote }}"
        type: "{{ item.type|default('nfs') }}"
        options: "{{ item.options|default('') }}"
        on_boot: "{{ item.on_boot|default(true) }}"
        lazy_unmount: "{{ item.lazy_unmount|default(false) }}"
        force_unmount: "{{ item.force_unmount|default(false) }}"
        mount_timeout: "{{ item.mount_timeout|default(30) }}"
        idle_timeout: "{{ item.idle_timeout|default(0) }}"
      loop: "{{ network_mounts|default([]) }}"
      loop_control:
        label: "{{ item.path }}"

    - name: "Setup Network Mounts: Install Systemd Automount Unit for Mount Points"
      ansible.builtin.template:
        dest: "/etc/systemd/system/{{ item.path|replace('/', '-')|regex_replace('^-') }}.automount"
        src: "{{ playbook_dir }}/files/etc/systemd/system/network.mounts.automount.j2"
        owner: "root"
        group: "root"
        mode: "0644"
      vars:
        path: "{{ item.path }}"
        remote: "{{ item.remote }}"
        type: "{{ item.type|default('nfs') }}"
        options: "{{ item.options|default('') }}"
        on_boot: "{{ item.on_boot|default(true) }}"
        lazy_unmount: "{{ item.lazy_unmount|default(false) }}"
        force_unmount: "{{ item.force_unmount|default(false) }}"
        mount_timeout: "{{ item.mount_timeout|default(30) }}"
        idle_timeout: "{{ item.idle_timeout|default(0) }}"
      when: "item.onboot|default(true)"
      loop: "{{ network_mounts|default([]) }}"
      loop_control:
        label: "{{ item.path }}"

    - name: "Setup Network Mounts: Enable Systemd Automount Unit for Mount Points"
      ansible.builtin.systemd_service:
        name: "{{ item.path|replace('/', '-')|regex_replace('^-') }}.automount"
        state: "started"
        enabled: true
        daemon_reload: true
      when: "item.onboot|default(true)"
      loop: "{{ network_mounts|default([]) }}"
      loop_control:
        label: "{{ item.path }}"


