

- import_playbook: "desktop.system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_desktop_enabled: true

  tasks:

    - name: "Setup Desktop Software"
      when: "software_desktop_enabled|default(false)"
      block:

        - name: "Setup Desktop Software: Install Desktop Software from Distribution"
          ansible.builtin.dnf:
            name:
              - "@multimedia"
              - "calibre"
              - "geeqie"
              - "gimp"
              - "intel-media-driver"
              - "inkscape"
              - "kdenlive"
              - "keepassxc"
              - "mpv"
              - "okteta"
              - "qbittorrent"
              - "skanlite"
              - "vlc"
            state: "latest"


