

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_postgresql_enabled: true

  tasks:

    - name: "Setup PostgreSQL Database Server"
      when: "software_postgresql_enabled|default(false)"
      block:

        - name: "Setup PostgreSQL Database Server: Install PostgreSQL from Distribution"
          ansible.builtin.dnf:
            name:
              - "postgresql"
              - "postgresql-contrib"
              - "postgresql-docs"
              - "postgresql-server"
              - "postgresql-upgrade"
            state: "latest"


