

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Block Devices: Install Tools from Distribution"
      ansible.builtin.dnf:
        name:
          - "exfatprogs"
          - "ntfs-3g"
          - "ntfsprogs"
          - "nvme-cli"
          - "smartmontools"
        state: "latest"

    - name: "Configuring Block Devices: Expose SMART Temperature of Block Devices"
      ansible.builtin.copy:
        dest: "/etc/modules-load.d/blockdev.conf"
        src: "{{ playbook_dir }}/files/desktop/etc/modules-load.d/blockdev.conf"
        owner: "root"
        group: "root"
        mode: "0644"


