

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    network_devices_packages:
      - "bridge-utils"
      - "wireguard-tools"

  tasks:

    - name: "Setup Network Devices: Enable Networkd"
      ansible.builtin.systemd_service:
        name: "systemd-networkd.service"
        state: "started"
        enabled: true
        daemon_reload: true

    - name: "Setup Network Devices: Install Helper Tools from Distribution"
      ansible.builtin.dnf:
        name: "{{ network_devices_packages }}"
        state: "latest"

    - name: "Setup Network Devices: Load Secrets from Vault"
      ansible.builtin.include_vars:
        file: "secrets/network.devices.vault"

    - name: "Setup Network Devices: Install Configuration Files"
      ansible.builtin.template:
        dest: "{{ item.1.template|replace('device', item.0.device) }}"
        src: "{{ playbook_dir }}/files/{{ item.1.template }}.j2"
        owner: "{{ item.1.owner|default('root') }}"
        group: "{{ item.1.group|default('root') }}"
        mode: "{{ item.1.mode|default('0644') }}"
      vars:
        device: "{{ item.0.device }}"
        options: "{{ item.1.options|default({}) }}"
      loop: "{{ network_devices|default({})|dict2items(key_name='device',value_name='files')|subelements('files') }}"
      loop_control:
        label: "{{ item.1.template|replace('device', item.0.device) }}"


