

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    software_arduino_enabled: true
    software_arduino_users: [ "kmchan" ]

  tasks:

    - name: "Setup Arduino"
      when: "software_arduino_enabled|default(false)"
      block:

        - name: "Setup Arduion Development Tools: Install Arduino IDE from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/cc.arduino.IDE2.flatpakref"
            state: "present"

        - name: "Setup Arduion Development Tools: Add Users to Dialout Group"
          ansible.builtin.user:
            name: "{{ item }}"
            groups: "dialout"
            append: true
          loop: "{{ software_arduino_users|default([]) }}"


