

- hosts: "desktop"
  become: true
  become_user: "root"

  vars:

    software_wine_enabled: true

  tasks:

    - name: "Setup Wine"
      when: "software_wine_enabled|default(false) and software_wine_from|default('distro') == 'distro'"
      block:

        - name: "Setup Wine: Install Wine from Distribution"
          ansible.builtin.dnf:
            name:
              - "wine-core"
              - "wine-alsa"
              - "wine-cms"
              - "wine-dxvk"
              - "wine-dxvk-d3d9"
              - "wine-dxvk-dxgi"
              - "wine-fonts"
              - "wine-ldap"
              - "wine-mono"
              - "wine-opencl"
              - "wine-pulseaudio"
              - "wine-twain"
              - "wine-core.i686"
              - "wine-alsa.i686"
              - "wine-cms.i686"
              - "wine-dxvk.i686"
              - "wine-dxvk-d3d9.i686"
              - "wine-dxvk-dxgi.i686"
              - "wine-ldap.i686"
              - "wine-opencl.i686"
              - "wine-pulseaudio.i686"
              - "wine-twain.i686"
              - "winetricks"
            state: "latest"


