

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Creating Guest Networks: Install Netplan Configuration"
      template:
        dest: "/etc/netplan/99-guest.yaml"
        src: "files/etc/netplan/99-guest.yaml.j2"
        owner: "root"
        group: "root"
        mode: "0600"
      notify:
        - "Reload Netplan Service"

  handlers:

    - name: "Reload Netplan Service"
      command: "netplan apply"


