

#- import_playbook: "hardware.kvm.yml"
#- import_playbook: "hardware.vfio.yml"
#- import_playbook: "install.qemu.yml"
#- import_playbook: "install.looking_glass.yml"
#- import_playbook: "install.piper.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    guest_data_prefix: "/var/lib/guest"
    guest_socket_prefix: "/var/run/guest"
    guest_ivshmem_prefix: "/dev/shm/guest"

    guest_files:
      - { path: "/etc/systemd/system/guest.service", mode: "0644" }
      - { path: "/etc/sudoers.d/guest", mode: "0600" }
      - { path: "/usr/local/bin/guest-start", mode: "0755" }
      - { path: "/usr/local/bin/guest-attach-usb", mode: "0755" }
      - { path: "/usr/local/bin/guest-detach-usb", mode: "0755" }
      - { path: "/usr/local/bin/guest-insert-cdrom", mode: "0755" }
      - { path: "/usr/local/bin/guest-eject-cdrom", mode: "0755" }
      - { path: "/usr/local/bin/guest-monitor", mode: "0755" }
      - { path: "/usr/local/bin/guest-viewer", mode: "0755" }
      - { path: "/usr/local/sbin/guest-daemon", mode: "0755" }
      - { path: "/usr/local/sbin/guest-initialize", mode: "0755" }
      - { path: "/usr/local/sbin/guest-finalize", mode: "0755" }
      - { path: "/usr/local/lib/guest/functions", mode: "0644", placeholder: "functions" }
      - { path: "/var/lib/guest/name/.asoundrc", mode: "0644", placeholder: "name" }

  tasks:

    - name: "Create Guest Instances: Create User Groups"
      group:
        name: "{{ item.account }}"
        state: "present"
        system: "yes"
      loop: "{{ guest_instances|default([]) }}"
 
    - name: "Create Guest Instances: Create Users"
      user:
        name: "{{ item.account }}"
        state: "present"
        system: "yes"
        home: "{{ guest_data_prefix }}/{{ item.name }}"
        shell: "/sbin/nologin"
        createhome: "yes"
        group: "{{ item.account }}"
        groups: "{{ item.groups|default([])|union(['input', 'kvm', 'plugdev', 'usbdev', 'vfio'])|join(',') }}"
      loop: "{{ guest_instances|default([]) }}"

    - name: "Create Guest Instances: Enable Admin Access to Guest Instances"
      user:
        name: "{{ item[1] }}"
        state: "present"
        groups: "{{ item[0].account }}"
        append: "yes"
      with_subelements:
        - "{{ guest_instances|default([]) }}"
        - "admins"

    - name: "Create Guest Instances: Create Necessary Directories"
      file:
        dest: "/usr/local/lib/guest"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Create Guest Instances: Install BIOS File"
      copy:
        dest: "/var/lib/guest/{{ item.name }}/"
        src: "/usr/share/OVMF/OVMF_VARS.fd"
        remote_src: "yes"
        owner: "{{ item.account }}"
        group: "{{ item.account }}"
        mode: "0644"
        force: "no"
      loop: "{{ guest_instances|default([]) }}"

    - name: "Create Guest Instances: Install Configuration Files"
      template:
        dest: "{{ item[1].path|replace(item[1].placeholder|default('guest'), item[0].name) }}"
        src: "{{ playbook_dir }}/files/{{ item[1].path }}.j2"
        owner: "root"
        group: "root"
        mode: "{{ item[1].mode }}"
      with_nested:
        - "{{ guest_instances|default([]) }}"
        - "{{ guest_files }}"


