

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Creating Guest Disks: Create User Groups"
      group:
        name: "{{ item.account }}"
        state: "present"
        system: "yes"
      when: "item.type is defined and item.account is defined"
      loop: "{{ guest_disks|default([]) }}"

    - name: "Creating Guest Disks: Create Users"
      user:
        name: "{{ item.account }}"
        state: "present"
        system: "yes"
        home: "/"
        createhome: "no"
        group: "{{ item.account }}"
      when: "item.type is defined and item.account is defined"
      loop: "{{ guest_disks|default([]) }}"

    - name: "Creating Guest Disks: Install Udev Rules"
      template:
        dest: "/etc/udev/rules.d/99-guest.rules"
        src: "files/etc/udev/rules.d/99-guest.rules.j2"
        owner: "root"
        group: "root"
        mode: "0600"
      notify:
        - "Reload Udev Service"
        - "Apply Udev Configuration"

  handlers:

    - name: "Reload Udev Service"
      command: "udevadm control --reload"

    - name: "Apply Udev Configuration"
      command: "udevadm trigger"


