

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring Video Cards: Enable Framebuffer Modules for Primary Cards"
      template:
        dest: "/etc/modules-load.d/video.conf"
        src: "{{ playbook_dir }}/files/etc/modules-load.d/video.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configuring Video Cards: Include Framebuffer Modules for Primary Cards in Initial RAM Disk"
      lineinfile:
        dest: "/etc/initramfs-tools/modules"
        regexp: '^\s*#?\s*{{ item.value["module"] }}.*$'
        line: '{{ item.value["module"] }}'
      when: "item.value['type'] == 'primary'"
      with_dict: "{{ hardware_video }}"
      notify: "Update Initial RAM Disk"

    - name: "Configuring Video Cards: Initialize Kernel Command Line"
      lineinfile:
        dest: "/etc/default/grub"
        regexp: '^\s*#\s*GRUB_CMDLINE_LINUX_DEFAULT=(?:"?\s*(.*?)\s*"?)?\s*$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1"'
        backrefs: "yes"
      notify: "Update GRUB Boot Loader"

    - name: "Configuring Video Cards: Disable EFI/VESA Framebuffer in Kernel Command Line"
      kernel_options_in_file:
        dest: "/etc/default/grub"
        region: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"$'
        state: 'present'
        target: 'option'
        option: 'video'
        value: 'vesafb:off,efifb:off'
      notify: "Update GRUB Boot Loader"

    - name: "Configuring Video Cards: Enable Primary Cards in X.org"
      template:
        dest: "/etc/X11/xorg.conf.d/10-devices.conf"
        src: "{{ playbook_dir }}/files/etc/X11/xorg.conf.d/10-devices.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Configuring Video Cards: Generate Bind Script for Each Passthrough Card"
      template:
        dest: "/usr/local/sbin/vfio-bind-video-{{ item.key }}"
        src: "{{ playbook_dir }}/files/usr/local/sbin/vfio-bind-video.j2"
        owner: "root"
        group: "root"
        mode: "0755"
      when: "item.value['type'] == 'passthrough'"
      with_dict: "{{ hardware_video }}"

    - name: "Configuring Video Cards: Generate Unbind Script for Each Passthrough Card"
      template:
        dest: "/usr/local/sbin/vfio-unbind-video-{{ item.key }}"
        src: "{{ playbook_dir }}/files/usr/local/sbin/vfio-unbind-video.j2"
        owner: "root"
        group: "root"
        mode: "0755"
      when: "item.value['type'] == 'passthrough'"
      with_dict: "{{ hardware_video }}"

  handlers:

    - name: "Update Initial RAM Disk"
      command: "update-initramfs -u -k all"

    - name: "Update GRUB Boot Loader"
      command: "update-grub"


