

- import_playbook: "system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Video Cards: Install Mesa VAAPI Drivers from RPM Fusion"
      ansible.builtin.shell:
        cmd: "dnf swap mesa-va-drivers mesa-va-drivers-freeworld"

    - name: "Configure Video Cards: Install Intel VAAPI Drivers from RPM Fusion"
      ansible.builtin.dnf:
        name:
          - "intel-media-driver"
          - "libva-intel-driver"
        state: "latest"

    - name: "Configure Video Cards: Install Nvidia Video Drivers from RPM Fusion"
      ansible.builtin.dnf:
        name:
          - "akmod-nvidia"
          - "kmod-nvidia"
          - "xorg-x11-drv-nvidia"
          - "xorg-x11-drv-nvidia-cuda"
          - "xorg-x11-drv-nvidia-cuda-libs"
          - "xorg-x11-drv-nvidia-libs"
          - "xorg-x11-drv-nvidia-power"
          - "xorg-x11-drv-nvidia-cuda-libs.i686"
          - "xorg-x11-drv-nvidia-libs.i686"
        state: "latest"

    - name: "Configuring Video Cards: Enable Primary Cards in X.org"
      ansible.builtin.template:
        dest: "/etc/X11/xorg.conf.d/10-devices.conf"
        src: "{{ playbook_dir }}/files/etc/X11/xorg.conf.d/10-devices.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"


