

#- import_playbook: "system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Video Cards: Install Mesa VAAPI Drivers from RPM Fusion"
      ansible.builtin.shell:
        cmd: "dnf swap mesa-va-drivers mesa-va-drivers-freeworld"

    - name: "Configure Video Cards: Install Intel VAAPI Drivers from RPM Fusion"
      ansible.builtin.dnf:
        name:
          - "intel-media-driver"
          - "libva-intel-driver"
        state: "latest"

    - name: "Configure Video Cards: Install Nvidia Video Drivers from RPM Fusion"
      ansible.builtin.dnf:
        name:
          - "akmod-nvidia"
          - "kmod-nvidia"
          - "xorg-x11-drv-nvidia"
          - "xorg-x11-drv-nvidia-cuda"
          - "xorg-x11-drv-nvidia-cuda-libs"
          - "xorg-x11-drv-nvidia-libs"
          - "xorg-x11-drv-nvidia-power"
          - "xorg-x11-drv-nvidia-cuda-libs.i686"
          - "xorg-x11-drv-nvidia-libs.i686"
        state: "latest"

    - name: "Configuring Video Cards: Create Configuration Directories"
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: "directory"
        owner: "{{ item.owner|default('root') }}"
        group: "{{ item.group|default('root') }}"
        mode: "{{ item.mode|default('0755') }}"
      loop:
        - { path: "/etc/environment.d" }
        - { path: "/etc/profile.d" }
        - { path: "/etc/udev/rules.d" }
        - { path: "/etc/X11" }
        - { path: "/etc/X11/xorg.conf.d" }
        - { path: "/opt/video" }
        - { path: "/opt/video/bin" }

    - name: "Configuring Video Cards: Install Configuration Files"
      ansible.builtin.template:
        dest: "{{ item.path }}"
        src: "{{ playbook_dir }}/files/{{ item.path }}.j2"
        owner: "{{ item.owner|default('root') }}"
        group: "{{ item.group|default('root') }}"
        mode: "{{ item.mode|default('0644') }}"
      loop:
        - { path: "/etc/environment.d/10-video.conf" }
        - { path: "/etc/profile.d/video.sh" }
        - { path: "/etc/udev/rules.d/99-video.rules" }
        - { path: "/etc/X11/xorg.conf.d/10-devices.conf" }
        - { path: "/opt/video/bin/disable-offload", mode: "0755" }
        - { path: "/opt/video/bin/enable-offload", mode: "0755" }
        - { path: "/opt/video/bin/prime-run", mode: "0755" }


