

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Block Devices: Install Tools from Distribution"
      ansible.builtin.dnf:
        name:
          - "exfatprogs"
          - "ntfs-3g"
          - "ntfsprogs"
          - "nvme-cli"
          - "smartmontools"
        state: "latest"


