

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring Hardware Sensors: Enable Kernel Modules"
      template:
        dest: "/etc/modules-load.d/sensor.conf"
        src: "{{ playbook_dir }}/files/etc/modules-load.d/sensor.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"
      when: "hardware_sensor_modules|default([])|length > 0"


