

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring USB Autosuspend: Initialize Kernel Command Line"
      lineinfile:
        dest: "/etc/default/grub"
        regexp: '^\s*#\s*GRUB_CMDLINE_LINUX_DEFAULT=(?:"?\s*(.*?)\s*"?)?\s*$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1"'
        backrefs: "yes"
      notify:
        - "Update GRUB Boot Loader"

    - name: "Configuring USB Autosuspend: Configure Autosuspend in Kernel Command Line"
      kernel_options_in_file:
        dest: "/etc/default/grub"
        region: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"$'
        target: 'option'
        state: 'present'
        option: 'usbcore.autosuspend'
        value: '{{ hardware_usb_autosuspend|default(2) }}'
      notify:
        - "Update GRUB Boot Loader"

    - name: "Configuring USB Raw Access: Create User Group"
      group:
        name: "usbdev"
        state: "present"
        system: "yes"

    - name: "Configuring USB Raw Access: Install Udev Rules"
      copy:
        dest: "/etc/udev/rules.d/98-raw-usb.rules"
        src: "files/etc/udev/rules.d/98-raw-usb.rules"
        owner: "root"
        group: "root"
        mode: "0600"
      notify:
        - "Reload Udev Service"
        - "Apply Udev Configuration"

  handlers:

    - name: "Update GRUB Boot Loader"
      command: "update-grub"

    - name: "Reload Udev Service"
      command: "udevadm control --reload"

    - name: "Apply Udev Configuration"
      command: "udevadm trigger"


