

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Generate Mosquitto Container Image: Start Buildah Container"
      ansible.builtin.command: "buildah from debian:latest"
      register: "container"

    - name: "Generate Mosquitto Container Image: Create Image from Buildah Container"
      block:

        - name: "Generate Mosquitto Container Image: Update Debian Package Database in Buildah Container"
          ansible.builtin.command: "buildah run {{ container['stdout'] }} -- apt update"

        - name: "Generate Mosquitto Container Image: Upgrade Debian Packages in Buildah Container"
          ansible.builtin.command: "buildah run {{ container['stdout'] }} -- apt upgrade -q -y"

        - name: "Generate Mosquitto Container Image: Install Mosquitto Package in Buildah Container"
          ansible.builtin.command: "buildah run {{ container['stdout'] }} -- apt install -q -y mosquitto"

        - name: "Generate Mosquitto Container Image: Create Directory for External Configuration Files"
          ansible.builtin.command: "buildah run {{ container['stdout'] }} -- mkdir -p /etc/mosquitto/container"

        - name: "Generate Mosquitto Container Image: Create Local Configuration File"
          ansible.builtin.command:
            cmd: "buildah run {{ container['stdout'] }} -- tee /etc/mosquitto/container.conf"
            stdin: "{{ lookup('file', playbook_dir ~ '/files/etc/mosquitto/container.conf') }}"

        - name: "Generate Mosquitto Container Image: Setup the Command Line"
          ansible.builtin.command: "buildah config --cmd '/usr/sbin/mosquitto -c /etc/mosquitto/container.conf' {{ container['stdout'] }}"

        - name: "Generate Mosquitto Container Image: Setup the User"
          ansible.builtin.command: "buildah config --user mosquitto {{ container['stdout'] }}"

        - name: "Generate Mosquitto Container Image: Setup the Working Directory"
          ansible.builtin.command: "buildah config --workingdir / {{ container['stdout'] }}"

        - name: "Generate Mosquitto Container Image: Setup the Ports"
          ansible.builtin.command: "buildah config --port 1883/tcp --port 8883/tcp --port 8080/tcp --port 8443/tcp {{ container['stdout'] }}"

        - name: "Generate Mosquitto Container Image: Setup the Volume"
          ansible.builtin.command: "buildah config --volume /etc/mosquitto/container/ {{ container['stdout'] }}"

        - name: "Generate Mosquitto Container Image: Commit Buildah Container to Image"
          ansible.builtin.command: "buildah commit {{ container['stdout'] }} mosquitto"

      always:

        - name: "Generate Mosquitto Container Image: Delete Buildah Container"
          ansible.builtin.command: "buildah rm {{ container['stdout'] }}"


