

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_wine_mono_lookup:
      - { wine: "7.6",   mono: "7.2.0",    url: "https://dl.winehq.org/wine/wine-mono/7.2.0/wine-mono-7.2.0-x86.tar.xz" }
      - { wine: "7.2",   mono: "7.1.1",    url: "https://dl.winehq.org/wine/wine-mono/7.1.1/wine-mono-7.1.1-x86.tar.xz" }
      - { wine: "6.22",  mono: "7.0.0",    url: "https://dl.winehq.org/wine/wine-mono/7.0.0/wine-mono-7.0.0-x86.tar.xz" }
      - { wine: "6.18",  mono: "6.4.0",    url: "https://dl.winehq.org/wine/wine-mono/6.4.0/wine-mono-6.4.0-x86.tar.xz" }
      - { wine: "6.14",  mono: "6.3.0",    url: "https://dl.winehq.org/wine/wine-mono/6.3.0/wine-mono-6.3.0-x86.tar.xz" }
      - { wine: "6.10",  mono: "6.2.0",    url: "https://dl.winehq.org/wine/wine-mono/6.2.0/wine-mono-6.2.0-x86.tar.xz" }
      - { wine: "6.6",   mono: "6.1.1",    url: "https://dl.winehq.org/wine/wine-mono/6.1.1/wine-mono-6.1.1-x86.tar.xz" }
      - { wine: "6.2",   mono: "6.0.0",    url: "https://dl.winehq.org/wine/wine-mono/6.0.0/wine-mono-6.0.0-x86.tar.xz" }
      - { wine: "5.19",  mono: "5.1.1",    url: "https://dl.winehq.org/wine/wine-mono/5.1.1/wine-mono-5.1.1-x86.tar.xz" }
      - { wine: "5.11",  mono: "5.1.0",    url: "https://dl.winehq.org/wine/wine-mono/5.1.0/wine-mono-5.1.0-x86.tar.xz" }
      - { wine: "5.7",   mono: "5.0.0",    url: "https://dl.winehq.org/wine/wine-mono/5.0.0/wine-mono-5.0.0-x86.tar.xz" }
      - { wine: "4.20",  mono: "4.9.4",    url: "https://dl.winehq.org/wine/wine-mono/4.9.4/wine-mono-bin-4.9.4.tar.gz" }
      - { wine: "4.17",  mono: "4.9.3",    url: "https://dl.winehq.org/wine/wine-mono/4.9.3/wine-mono-bin-4.9.3.tar.gz" }
      - { wine: "4.14",  mono: "4.9.2",    url: "https://dl.winehq.org/wine/wine-mono/4.9.2/wine-mono-bin-4.9.2.tar.gz" }
      - { wine: "4.11",  mono: "4.9.0",    url: "https://dl.winehq.org/wine/wine-mono/4.9.0/wine-mono-bin-4.9.0.tar.gz" }
      - { wine: "4.7",   mono: "4.8.3",    url: "https://dl.winehq.org/wine/wine-mono/4.8.3/wine-mono-bin-4.8.3.tar.gz" }
      - { wine: "4.6",   mono: "4.8.1",    url: "https://dl.winehq.org/wine/wine-mono/4.8.1/wine-mono-bin-4.8.1.tar.gz" }
      - { wine: "4.3",   mono: "4.8.0",    url: "https://dl.winehq.org/wine/wine-mono/4.8.0/wine-mono-bin-4.8.0.tar.gz" }
      - { wine: "4.0",   mono: "4.7.5",    url: "https://dl.winehq.org/wine/wine-mono/4.7.5/wine-mono-bin-4.7.5.tar.gz" }

    install_wine_gecko_lookup:
      - { wine: "6.0",   gecko: "2.47.2",  url: "http://dl.winehq.org/wine/wine-gecko/2.47.2/wine-gecko-2.47.2-ARCH.tar.xz" }
      - { wine: "5.0",   gecko: "2.47.1",  url: "http://dl.winehq.org/wine/wine-gecko/2.47.1/wine-gecko-2.47.1-ARCH.tar.bz2" }

  tasks:

    - name: "Install Wine from Distribution"
      when: "install_wine_enabled|default(false) and install_wine_from|default('distro') == 'distro'"
      block:

        - name: "Install Wine from Distribution: Remove Wine Packages from Upstream"
          apt:
            name: "{{ item.name }}"
            state: "absent"
          loop:
            - { name: "winehq-stable" }
            - { name: "winehq-staging" }
            - { name: "winehq-devel" }

        - name: "Install Wine from Distribution: Install Wine Packages from Distribution"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop:
            - { name: "wine" }
            - { name: "wine32" }
            - { name: "wine64" }

        - name: "Install Wine from Distribution: Pull Package List"
          package_facts:
            manager: "auto"

        - name: "Install Wine from Distribution: Check Installed Wine Version"
          set_fact:
            install_wine_version: "{{ (ansible_facts.packages['wine'][0]['version']|regex_search('([0-9a-z\\.]+)', '\\1'))[0] }}"
            install_wine_prefix: "/usr"

    - name: "Install Wine from Upstream"
      when: "install_wine_enabled|default(false) and install_wine_from|default('distro') == 'upstream'"
      block:

        - name: "Install Wine from Upstream: Install Upstream Package Signing Key"
          get_url:
            url: "https://dl.winehq.org/wine-builds/winehq.key"
            dest: "/usr/share/keyrings/winehq-archive.key"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Wine from Upstream: Install Upstream Package Source"
          get_url:
            url: "https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-{{ ansible_distribution_release|lower }}.sources"
            dest: "/etc/apt/sources.list.d/winehq-{{ ansible_distribution_release|lower }}.sources"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Wine from Upstream: Remove Wine Packages from Distribution"
          apt:
            name: "{{ item.name }}"
            state: "absent"
          loop:
            - { name: "wine" }
            - { name: "wine32" }
            - { name: "wine64" }

        - name: "Install Wine from Upstream: Install Wine Packages from Upstream"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop:
            - { name: "winehq-stable" }

        - name: "Install Wine from Upstream: Pull Package List"
          package_facts:
            manager: "auto"

        - name: "Install Wine from Upstream: Check Installed Wine Version"
          set_fact:
            install_wine_version: "{{ (ansible_facts.packages['winehq-stable'][0]['version']|regex_search('([0-9a-z\\.]+)', '\\1'))[0] }}"
            install_wine_prefix: "/opt/wine-stable"

    - name: "Install Wine"
      when: "install_wine_enabled|default(false)"
      block:

      - name: "Install Wine: Determine Wine Mono Version"
        set_fact:
          install_wine_mono_version: "{{ (install_wine_mono_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['mono'] }}"
          install_wine_mono_url:     "{{ (install_wine_mono_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['url'] }}"
          install_wine_mono_archive: "{{ ((install_wine_mono_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['url']|regex_search('/([^/]+)$', '\\1'))[0] }}"

      - name: "Install Wine: Create Wine Mono Directory"
        file:
          path: "{{ install_wine_prefix }}/share/wine/mono"
          state: "directory"
          owner: "root"
          group: "root"
          mode: "0755"

      - name: "Install Wine: Download Wine Mono Release Tarball"
        get_url:
          url: "{{ install_wine_mono_url }}"
          dest: "{{ install_wine_prefix }}/share/wine/mono/{{ install_wine_mono_archive }}"
          owner: "root"
          group: "root"
          mode: "0644"

      - name: "Install Wine: Unpack Wine Mono Release Tarball"
        shell: "tar --extract --no-same-owner --file {{ install_wine_mono_archive }}"
        args:
          chdir: "{{ install_wine_prefix }}/share/wine/mono"
          creates: "{{ install_wine_prefix }}/share/wine/mono/wine-mono-{{ install_wine_mono_version }}"
          warn: false

      - name: "Install Wine: Determine Wine Gecko Version"
        set_fact:
          install_wine_gecko_version: "{{ (install_wine_gecko_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['gecko'] }}"
          install_wine_gecko_url:     "{{ (install_wine_gecko_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['url'] }}"
          install_wine_gecko_archive: "{{ ((install_wine_gecko_lookup|selectattr('wine', 'version', install_wine_version, operator='le')|first)['url']|regex_search('/([^/]+)$', '\\1'))[0] }}"

      - name: "Install Wine: Create Wine Gecko Directory"
        file:
          path: "{{ install_wine_prefix }}/share/wine/gecko"
          state: "directory"
          owner: "root"
          group: "root"
          mode: "0755"

      - name: "Install Wine: Download Wine Gecko (x86 version) Release Tarball"
        get_url:
          url: "{{ install_wine_gecko_url|replace('ARCH', 'x86') }}"
          dest: "{{ install_wine_prefix }}/share/wine/gecko/{{ install_wine_gecko_archive|replace('ARCH', 'x86') }}"
          owner: "root"
          group: "root"
          mode: "0644"

      - name: "Install Wine: Unpack Wine Gecko (x86 version) Release Tarball"
        shell: "tar --extract --no-same-owner --file {{ install_wine_gecko_archive|replace('ARCH', 'x86') }}"
        args:
          chdir: "{{ install_wine_prefix }}/share/wine/gecko"
          creates: "{{ install_wine_prefix }}/share/wine/gecko/wine-gecko-{{ install_wine_gecko_version }}-x86"
          warn: false

      - name: "Install Wine: Download Wine Gecko (x86_64 version) Release Tarball"
        get_url:
          url: "{{ install_wine_gecko_url|replace('ARCH', 'x86_64') }}"
          dest: "{{ install_wine_prefix }}/share/wine/gecko/{{ install_wine_gecko_archive|replace('ARCH', 'x86_64') }}"
          owner: "root"
          group: "root"
          mode: "0644"

      - name: "Install Wine: Unpack Wine Gecko (x86_64 version) Release Tarball"
        shell: "tar --extract --no-same-owner --file {{ install_wine_gecko_archive|replace('ARCH', 'x86_64') }}"
        args:
          chdir: "{{ install_wine_prefix }}/share/wine/gecko"
          creates: "{{ install_wine_prefix }}/share/wine/gecko/wine-gecko-{{ install_wine_gecko_version }}-x86_64"
          warn: false


