


- import_playbook: "software.dpkg.yml"
- import_playbook: "install.node.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_emscripten_version: "1.38.41"
    install_emscripten_release: "releases-fastcomp-5c6785a63993ae7a4d5362b32b0be9c85138fb96-64bit"
    install_emscripten_url: "https://github.com/emscripten-core/emsdk"
    install_emscripten_directory: "/usr/local/lib/emscripten-1.38.41"
    install_emscripten_binaries:
      - { name: "emsdk", target: "emsdk" }
      - { name: "em-config", target: "fastcomp/emscripten/em-config" }
      - { name: "em++", target: "fastcomp/emscripten/em++" }
      - { name: "emar", target: "fastcomp/emscripten/emar" }
      - { name: "emcc", target: "fastcomp/emscripten/emcc" }
      - { name: "emcmake", target: "fastcomp/emscripten/emcmake" }
      - { name: "emconfigure", target: "fastcomp/emscripten/emconfigure" }
      - { name: "emmake", target: "fastcomp/emscripten/emmake" }
      - { name: "emranlib", target: "fastcomp/emscripten/emranlib" }
      - { name: "emrun", target: "fastcomp/emscripten/emrun" }
      - { name: "emscons", target: "fastcomp/emscripten/emscons" }

  tasks:

    - name: "Install Emscripten Toolchain"
      when: "install_emscripten_enabled|default(false)"
      block:

        - name: "Install Emscripten Toolchain: Clone SDK Installer"
          git:
            dest: "{{ install_emscripten_directory }}"
            repo: "{{ install_emscripten_url }}"
            clone: "yes"
            update: "yes"
            remote: "origin"
            accept_hostkey: "yes"

        - name: "Install Emscripten Toolchain: Install Emscripten Release"
          shell: "./emsdk install {{ install_emscripten_release }}"
          args:
            chdir: "{{ install_emscripten_directory }}"
            creates: "{{ install_emscripten_directory }}/fastcomp"
            warn: false

        - name: "Install Emscripten Toolchain: Symlink Executables"
          file:
            path: "/usr/local/bin/{{ item.name }}"
            src: "{{ install_emscripten_directory }}/{{ item.target }}"
            state: "link"
            force: true
          loop: "{{ install_emscripten_binaries }}"


