

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_node_version: "14.16.0"
    install_node_url: "https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-x64.tar.xz"
    install_node_checksum: "sha256:2e079cf638766fedd720d30ec8ffef5d6ceada4e8b441fc2a093cb9a865f4087"
    install_node_archive: "/usr/local/lib/node-14.16.0/node-v14.16.0.tar.xz"
    install_node_directory: "/usr/local/lib/node-14.16.0"
    install_node_binaries:
      - { name: node, target: node }
      - { name: nodejs, target: node }
      - { name: npm, target: npm }

    install_yarn_version: "1.22.10"
    install_yarn_url: "https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-v1.22.10.tar.gz"
    install_yarn_checksum: "sha256:7e433d4a77e2c79e6a7ae4866782608a8e8bcad3ec6783580577c59538381a6e"
    install_yarn_archive: "/usr/local/lib/yarn-1.22.10/yarn-v1.22.10.tar.gz"
    install_yarn_directory: "/usr/local/lib/yarn-1.22.10"
    install_yarn_binaries:
      - { name: "yarn", target: "yarn" }

  tasks:

    - name: "Install Node Toolchain"
      when: "install_node_enabled|default(false)"
      block:

        - name: "Install Node Toolchain: Create Node Installation Directory"
          file:
            path: "{{ install_node_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Node Toolchain: Download Node Release"
          get_url:
            url: "{{ install_node_url }}"
            dest: "{{ install_node_archive }}"
            checksum: "{{ install_node_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Node Toolchain: Unpack Node Release"
          shell: "tar --extract --no-same-owner --strip-components 1 --file {{ install_node_archive }}"
          args:
            chdir: "{{ install_node_directory }}"
            creates: "{{ install_node_directory }}/bin/node"
            warn: false

        - name: "Install Node Toolchain: Symlink Node Executables"
          file:
            path: "/usr/local/bin/{{ item.name }}"
            src: "{{ install_node_directory }}/bin/{{ item.target }}"
            state: "link"
            force: true
          loop: "{{ install_node_binaries }}"

        - name: "Install Node Toolchain: Create Yarn Installation Directory"
          file:
            path: "{{ install_yarn_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Node Toolchain: Download Yarn Release"
          get_url:
            url: "{{ install_yarn_url }}"
            dest: "{{ install_yarn_archive }}"
            checksum: "{{ install_yarn_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Node Toolchain: Unpack Yarn Release"
          shell: "tar --extract --no-same-owner --strip-components 1 --file {{ install_yarn_archive }}"
          args:
            chdir: "{{ install_yarn_directory }}"
            creates: "{{ install_yarn_directory }}/bin/node"
            warn: false

        - name: "Install Node Toolchain: Symlink Yarn Executables"
          file:
            path: "/usr/local/bin/{{ item.name }}"
            src: "{{ install_yarn_directory }}/bin/{{ item.target }}"
            state: "link"
            force: true
          loop: "{{ install_yarn_binaries }}"

