

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Install Skype"
      when: "install_skype_enabled|default(false)"
      block:

        - name: "Install Skype: Install Packages"
          apt:
            deb: "https://repo.skype.com/latest/skypeforlinux-64.deb"
            state: "present"
            allow_unauthenticated: true
            update_cache: true
            cache_valid_time: 86400

        - name: "Install Skype: Install Custom Profile Modification for Electron Apps"
          template:
            dest: "/etc/firejail/electron.local"
            src: "{{ playbook_dir }}/files/etc/firejail/electron.local.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Skype: Install Custom AppArmor Rule for Firejail"
          lineinfile:
            path: "/etc/apparmor.d/local/firejail-default"
            line: "/{,run/firejail/mnt/oroot/}usr/share/skypeforlinux/** ix,"
            state: "present"


