

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_looking_glass_version: "B3"
    install_looking_glass_url: "https://github.com/gnif/LookingGlass/"
    install_looking_glass_directory: "/usr/local/lib/LookingGlass-B3"

    install_looking_glass_dependencies:
      - { name: "binutils-dev" }
      - { name: "build-essential" }
      - { name: "cmake" }
      - { name: "fonts-freefont-ttf" }
      - { name: "libfontconfig1-dev" }
      - { name: "libsdl2-dev" }
      - { name: "libsdl2-ttf-dev" }
      - { name: "libssl-dev" }
      - { name: "libspice-protocol-dev" }
      - { name: "libx11-dev" }
      - { name: "nettle-dev" }
      - { name: "wayland-protocols" }

  tasks:

    - name: "Install Looking Glass"
      when: "install_looking_glass_enabled|default(false)"
      block:

        - name: "Install Looking Glass: Install Dependencies"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_looking_glass_dependencies|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Install Looking Glass: Clone Source Repository"
          git:
            dest: "{{ install_looking_glass_directory }}"
            repo: "{{ install_looking_glass_url }}"
            version: "{{ install_looking_glass_version }}"
            clone: "yes"
            update: "yes"
            remote: "origin"
            accept_hostkey: "yes"

        - name: "Install Looking Glass: Configure Source"
          shell: "cmake -DENABLE_BACKTRACE=0 ."
          args:
            chdir: "{{ install_looking_glass_directory }}/client"
            creates: "{{ install_looking_glass_directory }}/client/Makefile"
            warn: false


        - name: "Install Looking Glass: Compile Source"
          shell: "make"
          args:
            chdir: "{{ install_looking_glass_directory }}/client"
            creates: "{{ install_looking_glass_directory }}/client/looking-glass-client"
            warn: false

        - name: "Install Looking Glass: Symlink Executables"
          file:
            path: "/usr/local/bin/looking-glass-client"
            src: "{{ install_looking_glass_directory }}/client/looking-glass-client"
            state: "link"
            force: true


