

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_conky_version: "1.10.8"
    install_conky_url: "http://archive.ubuntu.com/ubuntu/pool/universe/c/conky/conky_1.10.8.orig.tar.gz"
    install_conky_checksum: "sha256:2ebd655a27c816bd613538b71d4ec1c096252cb522feaa05f64781dcedea8857"
    install_conky_archive: "/usr/local/lib/conky-1.10.8/conky_1.10.8.orig.tar.gz"
    install_conky_directory: "/usr/local/lib/conky-1.10.8"

    install_conky_patches:
      - { name: "hddtemp", file: "hddtemp.patch", creates: "src/hddtemp.cc.orig.hddtemp" }

    install_conky_dependencies:
      - { name: "build-essential" }
      - { name: "cmake" }
      - { name: "libcairo2-dev" }
      - { name: "libcurl4-openssl-dev" }
      - { name: "libimlib2-dev" }
      - { name: "libiw-dev" }
      - { name: "liblua5.1-0-dev" }
      - { name: "libncurses5-dev" }
      - { name: "libpulse-dev" }
      - { name: "librsvg2-dev" }
      - { name: "libsystemd-dev" }
      - { name: "libtinfo-dev" }
      - { name: "libtolua++5.1-dev" }
      - { name: "libx11-dev" }
      - { name: "libxdamage-dev" }
      - { name: "libxext-dev" }
      - { name: "libxft-dev" }
      - { name: "libxfixes-dev" }
      - { name: "libxinerama-dev" }
      - { name: "libxml2-dev" }
      - { name: "libxnvctrl-dev" }
      - { name: "pkg-config" }

  tasks:

    - name: "Install Conky"
      when: "install_conky_enabled|default(false)"
      block:

        - name: "Install Conky: Install Dependencies"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_conky_dependencies|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Install Conky: Create Installation Directory"
          file:
            path: "{{ install_conky_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Conky: Download Source"
          get_url:
            url: "{{ install_conky_url }}"
            dest: "{{ install_conky_archive }}"
            checksum: "{{ install_conky_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Conky: Download Patches"
          copy:
            dest: "{{ install_conky_directory }}/{{ item.file }}"
            src: "files/{{ install_conky_directory }}/{{ item.file }}"
            owner: "root"
            group: "root"
            mode: "0644"
          loop: "{{ install_conky_patches }}"

        - name: "Install Conky: Unpack Source"
          shell: "tar --extract --no-same-owner --strip-components 1 --file {{ install_conky_archive }}"
          args:
            chdir: "{{ install_conky_directory }}"
            creates: "{{ install_conky_directory }}/README.md"
            warn: false

        - name: "Install Conky: Patch Source"
          shell: "cat {{ item.file }} | patch -p1 -b -V simple -z .orig.{{ item.name }}"
          args:
            chdir: "{{ install_conky_directory }}"
            creates: "{{ install_conky_directory }}/{{ item.creates }}"
          loop: "{{ install_conky_patches }}"

        - name: "Install Conky: Configure Source"
          shell: "cmake . -DBUILD_APCUPSD=ON -DBUILD_ARGB=ON -DBUILD_CURL=ON -DBUILD_EVE=ON -DBUILD_HDDTEMP=ON -DBUILD_I18N=ON -DBUILD_IBM=ON -DBUILD_IMLIB2=ON -DBUILD_IOSTATS=ON -DBUILD_IPV6=ON -DBUILD_JOURNAL=ON -DBUILD_LUA_CAIRO=ON -DBUILD_LUA_IMLIB2=ON -DBUILD_LUA_RSVG=ON -DBUILD_MATH=ON -DBUILD_NCURSES=ON -DBUILD_NVIDIA=ON -DBUILD_PORT_MONITORS=ON -DBUILD_PULSEAUDIO=ON -DBUILD_RSS=ON -DBUILD_WEATHER_METAR=ON -DBUILD_WEATHER_XOAP=ON -DBUILD_WLAN=ON -DBUILD_X11=ON -DBUILD_XDAMAGE=ON -DBUILD_XDBE=ON -DBUILD_XFT=ON -DBUILD_XINERAMA=ON -DBUILD_XSHAPE=ON -DOWN_WINDOW=ON"
          args:
            chdir: "{{ install_conky_directory }}"
            creates: "{{ install_conky_directory }}/Makefile"
            warn: false

        - name: "Install Conky: Compile Source"
          shell: "make"
          args:
            chdir: "{{ install_conky_directory }}"
            creates: "{{ install_conky_directory }}/src/conky"
            warn: false

        - name: "Install Conky: Symlink Executables"
          file:
            path: "/usr/local/bin/conky"
            src: "{{ install_conky_directory }}/src/conky"
            state: "link"
            force: true


