

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_java_releases:
      - { version:  7, requires: { distribution: "debian", since: "jessie", until: "jessie" } }
      - { version:  8, requires: { distribution: "debian", since: "jessie" } }
      - { version: 11, requires: { distribution: "debian", since: "stretch" } }
      - { version:  6, requires: { distribution: "ubuntu", since: "trusty", until: "trusty" } }
      - { version:  7, requires: { distribution: "ubuntu", since: "trusty", until: "trusty" } }
      - { version:  8, requires: { distribution: "ubuntu", since: "xenial" } }
      - { version: 11, requires: { distribution: "ubuntu", since: "bionic" } }

    install_java_packages:
      - { name: "ant" }
      - { name: "ant-contrib" }
      - { name: "ant-optional" }
      - { name: "gradle" }
      - { name: "ivy" }
      - { name: "libgradle-plugins-java" }
      - { name: "maven" }
      - { name: "maven-ant-helper" }

  tasks:

    - name: "Install Java Toolchain"
      when: "install_java_enabled|default(false)"
      block:

        - name: "Install Java Toolchain: Install JRE Packages"
          apt:
            name: "{{ 'openjdk-XXX-jre'|replace('XXX', item.version) }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_java_releases|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Install Java Toolchain: Install JDK Packages"
          apt:
            name: "{{ 'openjdk-XXX-jdk'|replace('XXX', item.version) }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_java_releases|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Install Java Toolchain: Install Development Tools"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_java_packages|select('distribution', distro, release, attribute='requires')|list }}"

