

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_scream_version: "3.3"
    install_scream_url: "https://github.com/duncanthrax/scream/archive/3.3.tar.gz"
    install_scream_checksum: "sha256:4a8e390c7040cb5c20864db885e1883dc0df6fe515bc34bbe8c2455a1a827c76"
    install_scream_archive: "/usr/local/lib/scream-3.3/scream-3.3.tar.gz"
    install_scream_directory: "/usr/local/lib/scream-3.3"

    install_scream_dependencies:
      - { name: "build-essential" }
      - { name: "libpulse-dev" }

  tasks:

    - name: "Install Scream"
      when: "install_scream_enabled|default(false)"
      block:

        - name: "Install Scream: Install Dependencies"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_scream_dependencies|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Install Scream: Create Installation Directory"
          file:
            path: "{{ install_scream_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Scream: Download Source"
          get_url:
            url: "{{ install_scream_url }}"
            dest: "{{ install_scream_archive }}"
            checksum: "{{ install_scream_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Scream: Unpack Source"
          shell: "tar --extract --no-same-owner --strip-components 1 --file {{ install_scream_archive }}"
          args:
            chdir: "{{ install_scream_directory }}"
            creates: "{{ install_scream_directory }}/README.md"
            warn: false

        - name: "Install Scream: Compile Source"
          shell: "make"
          args:
            chdir: "{{ install_scream_directory }}/Receivers/pulseaudio-ivshmem"
            creates: "{{ install_scream_directory }}/Receivers/pulseaudio-ivshmem/scream-ivshmem-pulse"
            warn: false

        - name: "Install Scream: Symlink Executables"
          file:
            path: "/usr/local/bin/scream-ivshmem-pulse"
            src: "{{ install_scream_directory }}/Receivers/pulseaudio-ivshmem/scream-ivshmem-pulse"
            state: "link"
            force: true


