

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_golang_version: "1.15.8"
    install_golang_url: "https://golang.org/dl/go1.15.8.linux-amd64.tar.gz"
    install_golang_checksum: "sha256:d3379c32a90fdf9382166f8f48034c459a8cc433730bc9476d39d9082c94583b"
    install_golang_archive: "/usr/local/lib/golang-1.15.8/golang-1.15.8.tar.gz"
    install_golang_directory: "/usr/local/lib/golang-1.15.8"
    install_golang_binaries: [ "go", "godoc", "gofmt" ]

  tasks:

    - name: "Install Golang Toolchain"
      when: "install_golang_enabled|default(false)"
      block:

        - name: "Install Golang Toolchain: Create Installation Directory"
          file:
            path: "{{ install_golang_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Golang Toolchain: Download Release"
          get_url:
            url: "{{ install_golang_url }}"
            dest: "{{ install_golang_archive }}"
            checksum: "{{ install_golang_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Golang Toolchain: Unpack Release"
          shell: "tar --extract --no-same-owner --strip-components 1 --file {{ install_golang_archive }}"
          args:
            chdir: "{{ install_golang_directory }}"
            creates: "{{ install_golang_directory }}/bin/go"
            warn: false

        - name: "Install Golang Toolchain: Symlink Executables"
          file:
            path: "/usr/local/bin/{{ item }}"
            src: "{{ install_golang_directory }}/bin/{{ item }}"
            state: "link"
            force: true
          loop: "{{ install_golang_binaries }}"


