

- import_playbook: "software.dpkg.yml"
- import_playbook: "install.java.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_android_studio_version: "4.2"
    install_android_studio_url: "https://redirector.gvt1.com/edgedl/android/studio/ide-zips/4.2.0.24/android-studio-ide-202.7322048-linux.tar.gz"
    install_android_studio_checksum: "sha256:9f3132d181bfe4d46aca667fddf2557f3c428b6c6c726e0ac5be9f5d91fb21c6"
    install_android_studio_archive: "/usr/local/lib/android-studio-4.2/android-studio-ide-202.7322048-linux.tar.gz"
    install_android_studio_directory: "/usr/local/lib/android-studio-4.2"

  tasks:

    - name: "Install Android Studio"
      when: "install_android_studio_enabled|default(false)"
      block:

        - name: "Install Android Studio: Create Installation Directory"
          file:
            path: "{{ install_android_studio_directory }}"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Install Android Studio: Download Release"
          get_url:
            url: "{{ install_android_studio_url }}"
            dest: "{{ install_android_studio_archive }}"
            checksum: "{{ install_android_studio_checksum }}"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Install Android Studio: Unpack Release"
          shell: "bsdtar --extract --no-same-owner --strip-components 1 --file {{ install_android_studio_archive }}"
          args:
            chdir: "{{ install_android_studio_directory }}"
            creates: "{{ install_android_studio_directory }}/bin/stduio.sh"
            warn: false

        - name: "Install Android Studio: Symlink Executables"
          file:
            path: "/usr/local/bin/android-studio"
            src: "{{ install_android_studio_directory }}/bin/studio.sh"
            state: "link"
            force: true

        - name: "Install Android Studio: Install Desktop Entry"
          template:
            dest: "/usr/local/share/applications/android-studio.desktop"
            src: "{{ playbook_dir }}/files/usr/local/share/applications/android-studio.desktop.j2"
            owner: "root"
            group: "root"
            mode: "0644"


