

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_desktop_packages:
      - { name: "chromium" }
      - { name: "conky" }
      - { name: "fcitx" }
      - { name: "fcitx-table-all" }
      - { name: "fcitx-table-cangjie3" }
      - { name: "fcitx-table-cangjie5" }
      - { name: "fcitx-table-quick3" }
      - { name: "fcitx-table-quick5" }
      - { name: "geeqie" }
      - { name: "gimp" }
      - { name: "gtk2-engines-oxygen" }
      - { name: "gtk3-engines-breeze" }
      - { name: "keepassx" }
      - { name: "qbittorrent" }
      - { name: "skanlite" }
      - { name: "steam" }
      - { name: "tlp" }
      - { name: "vlc" }
      - { name: "wmctrl" }
      - { name: "xdotool" }
      - { name: "xpra" }

  tasks:

    - name: "Install Desktop Software"
      when: "install_desktop_enabled|default(false)"
      block:

        - name: "Install Desktop Software"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_desktop_packages|select('distribution', distro, release, attribute='requires')|list }}"


