

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_php_composer_version: "2.3.5"
    install_php_composer_url: "https://github.com/composer/composer/releases/download/2.3.5/composer.phar"
    install_php_composer_checksum: "sha256:3b3b5a899c06a46aec280727bdf50aad14334f6bc40436ea76b07b650870d8f4"

  tasks:

    - name: "Install PHP Toolchain"
      when: "install_php_enabled|default(false)"
      block:

        - name: "Install PHP Toolchain: Install PHP Runtime Packages"
          apt:
            name: "{{ php_component_prefix }}-{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ php_components }}"

        - name: "Install PHP Toolchain: Install PHP PECL Packages"
          apt:
            name: "{{ php_extension_prefix }}-{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ php_extensions }}"

        - name: "Install PHP Toolchain: Install Composer"
          get_url:
            url: "{{ install_php_composer_url }}"
            dest: "/usr/local/bin/composer"
            checksum: "{{ install_php_composer_checksum }}"
            owner: "root"
            group: "root"
            mode: "0755"


