

- import_playbook: "software.dpkg.yml"
- import_playbook: "install.java.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    install_arduino_packages:
      - { name: "arduino" }

  tasks:

    - name: "Install Arduino Integrated Development Environment"
      when: "install_arduino_enabled|default(false)"
      block:

        - name: "Install Arduino Integrated Development Environment: Install Required Packages"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ install_arduino_packages|select('distribution', distro, release, attribute='requires')|list }}"


