

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Install Baidu Net Disk"
      when: "install_baidunetdisk_enabled|default(false)"
      block:

        - name: "Install Baidu Net Disk: Install Dependencies"
          apt:
            name: "desktop-file-utils"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ ansible_distribution_release }}"

        - name: "Install Baidu Net Disk: Install Packages"
          apt:
            deb: "https://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/4.3.0/baidunetdisk_4.3.0_amd64.deb"
            state: "present"
            allow_unauthenticated: true
            update_cache: true
            cache_valid_time: 86400


