

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring Initial RAM Disk Network Settings: Include Modules in Initial RAM Disk"
      lineinfile:
        dest: "/etc/initramfs-tools/modules"
        regexp: '^\s*#?\s*{{ item }}.*$'
        line: '{{ item }}'
      with_items: "{{ network_initramfs_modules }}"
      notify: "Update Initial RAM Disk"

    - name: "Configuring Initial RAM Disk Network Settings: Reset Initramfs Network Configuration"
      copy:
        dest: "/etc/initramfs-tools/scripts/init-bottom/deconfigure-interfaces"
        src: "files/etc/initramfs-tools/scripts/init-bottom/deconfigure-interfaces"
        owner: "root"
        group: "root"
        mode: "0755"
      when: "network_initramfs_reset_netplan == true"
      notify:
        - "Update Initial RAM Disk"

  handlers:

    - name: "Update Initial RAM Disk"
      command: "update-initramfs -u -k all"


