

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring Network Modules: Enable Kernel Modules"
      template:
        dest: "/etc/modules-load.d/network.conf"
        src: "{{ playbook_dir }}/files/etc/modules-load.d/network.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"

