

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Configuring Network Devices: Install Netplan Configuration"
      template:
        dest: "/etc/netplan/99-network-devices.yaml"
        src: "files/etc/netplan/99-network-devices.yaml.j2"
        owner: "root"
        group: "root"
        mode: "0644"
      notify:
        - "Reload Netplan Service"

  handlers:

    - name: "Reload Netplan Service"
      command: "netplan apply"


