

- hosts: "server"
  become: true
  become_user: "root"

  vars:

    software_php_enabled: true

  tasks:

    - name: "Setup PHP Runtime"
      when: "software_php_enabled|default(false)"
      block:

        - name: "Setup PHP Runtime: Install PHP from Distribution"
          ansible.builtin.dnf:
            name:
              - "composer"
              - "php-bcmath"
              - "php-cli"
              - "php-dba"
              - "php-dbg"
              - "php-enchant"
              - "php-ffi"
              - "php-gd"
              - "php-gmp"
              - "php-intl"
              - "php-ldap"
              - "php-mbstring"
              - "php-mysqlnd"
              - "php-opcache"
              - "php-pdo"
              - "php-pgsql"
              - "php-process"
              - "php-pspell"
              - "php-soap"
              - "php-sodium"
              - "php-tidy"
              - "php-xml"
            state: "latest"


