

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup PHP FPM Service"
      when: "service_php_fpm_enabled|default(false)"
      block:

        - name: "Setup PHP FPM Service: Install PHP FPM Packages"
          apt:
            name: "{{ php_component_prefix }}-fpm"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ ansible_distribution_release }}"

        - name: "Setup PHP FPM Service: Enable PHP FPM Daemon"
          service:
            name: "{{ php_fpm_service }}"
            enabled: true


