

- hosts: "server"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Driverctl: Install Driverctl Utility"
      ansible.builtin.dnf:
        name: "driverctl"
        state: "latest"


