

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    service_apache_packages:
      - { name: "apache2" }
      - { name: "apache2-dev" }

  tasks:

    - name: "Setup Apache Service"
      when: "service_apache_enabled|default(false)"
      block:

        - name: "Setup Apache Service: Find Usable SSL Certificates"
          find:
            paths: "/etc/letsencrypt/live/"
            file_type: "directory"
            recurse: false
          register: "certificates"

        - name: "Setup Apache Service: Install Apache Packages"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ service_apache_packages|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Setup Apache Service: Create Required Directories"
          file:
            dest: "{{ item.path }}"
            state: "directory"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0755') }}"
          loop:
            - { path: "/etc/systemd/system/apache2.service.d" }
            - { path: "/etc/apache2/includes/" }

        - name: "Setup Apache Service: Install Configuration Files"
          template:
            dest: "{{ item.path }}"
            src: "files/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0644') }}"
          loop:
            - { path: "/etc/systemd/system/apache2.service.d/local.conf" }
            - { path: "/etc/apache2/conf-available/apache2-overrides.conf" }
            - { path: "/etc/apache2/conf-available/ports-overrides.conf" }
            - { path: "/etc/apache2/conf-available/security-overrides.conf" }
            - { path: "/etc/apache2/conf-available/ssl-overrides.conf" }
            - { path: "/etc/apache2/sites-available/000-local.conf" }
            - { path: "/etc/apache2/sites-available/000-local-ssl.conf" }
            - { path: "/etc/apache2/proxy.off.inc" }
            - { path: "/etc/apache2/proxy.on.inc" }
            - { path: "/etc/apache2/includes/proxy.conf" }
            - { path: "/var/www/html/index.html" }

        - name: "Setup Apache Service: Enable Modules"
          shell: "a2enmod -q remoteip rewrite socache_shmcb ssl"

        - name: "Setup Apache Service: Disable Modules"
          shell: "a2dismod -q status"

        - name: "Setup Apache Service: Enable Configurations"
          shell: "a2enconf -q apache2-overrides ports-overrides security-overrides ssl-overrides"

        - name: "Setup Apache Service: Disable Configurations"
          shell: "a2disconf -q serve-cgi-bin"

        - name: "Setup Apache Service: Enable Site over HTTP"
          shell: "a2ensite -q 000-local"

        - name: "Setup Apache Service: Enable Site over HTTPS"
          shell: "a2ensite -q 000-local-ssl"
          when: "'/etc/letsencrypt/live/' ~ service_apache_default_virtual_host in certificates.files|map(attribute='path')"

        - name: "Setup Apache Service: Disable Site"
          shell: "a2dissite -q 000-default default-ssl"

        - name: "Setup Apache Service: Enable Apache Daemon"
          service:
            name: "apache2.service"
            enabled: true


