

- import_playbook: "software.dpkg.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    service_bumblebee_dependencies:
      - { name: "bumblebee" }
      - { name: "bumblebee-nvidia" }
      - { name: "primus" }
      - { name: "primus-nvidia" }
      - { name: "nvidia-driver" }

  tasks:

    - name: "Setup Bumblebee Service"
      when: "service_bumblebee_enabled|default(false)"
      block:

        - name: "Setup Bumblebee Service: Create Necessary Directories"
          file:
            path: "{{ item.path }}"
            state: "directory"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.owner|default('root') }}"
            mode: "{{ item.mode|default('0755') }}"
          loop:
            - { path: "/etc/systemd/system/bumblebeed.service.d" }

        - name: "Setup Bumblebee Service: Install Packages"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ service_bumblebee_dependencies|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Setup Bumblebee Service: Select Primus Backend"
          lineinfile:
            path: "/etc/bumblebee/bumblebee.conf"
            line: "Bridge=primus"
            regexp: "^#?Bridge=(.*)$"
            state: "present"

        - name: "Setup Bumblebee Service: Select Xorg Video Driver"
          lineinfile:
            path: "/etc/bumblebee/bumblebee.conf"
            line: "Driver=nvidia"
            regexp: "^#?Driver=(.*)$"
            state: "present"

        - name: "Setup Bumblebee Service: Set Xorg Video Device"
          lineinfile:
            path: "/etc/bumblebee/xorg.conf.nvidia"
            line: "    BusID \"PCI:{{ hardware_pci_devices[service_bumblebee_device]['addresses'][0]|pciaddr('xorg') }}\""
            regexp: "^#?\\s*BusID\\s+(.*)$"
            state: "present"

        - name: "Setup Bumblebee Service: Disable Xorg DPMS setting"
          lineinfile:
            path: "/etc/bumblebee/xorg.conf.nvidia"
            line: "    Option \"HardDPMS\" \"false\""
            regexp: "^#?\\s*Option\\s+\"HardDPMS\"(.*)$"
            insertbefore: "^EndSection$"
            state: "present"

        - name: "Setup Bumblebee Service: Setup Local Bumblebee Service Options"
          template:
            dest: "/etc/systemd/system/bumblebeed.service.d/local.conf"
            src: "{{ playbook_dir }}/files/etc/systemd/system/bumblebeed.service.d/local.conf.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Setup Bumblebee Service: Setup Primus VK environment variables"
          template:
            dest: "/etc/profile.d/bumblebee.sh"
            src: "{{ playbook_dir }}/files/etc/profile.d/bumblebee.sh.j2"
            owner: "root"
            group: "root"
            mode: "0644"


        - name: "Setup Bumblebee Service: Enable Bumblebee Daemon"
          service:
            name: "bumblebeed.service"
            enabled: true


