

- import_playbook: "server.software.podman.yml"


- hosts: "server"
  become: true
  become_user: "root"

  vars:

    service_home_assistant_enabled: true
    service_home_assistant_domain: "home.kmchan3.space"
    service_home_assistant_timezone: "Asia/Hong_Kong"
    service_home_assistant_firewall_zones: [ "home", "internal", "work" ]

  tasks:

    - name: "Setup Home Assistant Service"
      when: "service_home_assistant_enabled|default(false)"
      block:

        - name: "Setup Home Assistant Service: Create Configuration Directory"
          ansible.builtin.file:
            dest: "/etc/home_assistant"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0750"

        - name: "Setup Home Assistant Service: Install Podman Quadlet File"
          ansible.builtin.template:
            dest: "/etc/containers/systemd/home_assistant.container"
            src: "{{ playbook_dir }}/files/common/etc/containers/systemd/home_assistant.container.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Setup Home Assistant Service: Install Firewalld Configuration File"
          ansible.builtin.template:
            dest: "/etc/firewalld/services/home_assistant.xml"
            src: "{{ playbook_dir }}/files/common/etc/firewalld/services/home_assistant.xml.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Setup Home Assistant Service: Enable Firewalld Service"
          ansible.posix.firewalld:
            zone: "{{ item }}"
            service: "home_assistant"
            state: "enabled"
            permanent: true
            offline: true
          loop: "{{ service_home_assistant_firewall_zones|default([]) }}"
          retries: 3
          delay: 5


