

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Certbot Service"
      when: "service_certbot_enabled|default(false)"
      block:

        - name: "Setup Certbot Service: Install Certbot Package"
          apt:
            name: "certbot"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ ansible_distribution_release }}"

        - name: "Setup Certbot Service: Configure Path for Webroot Authenticator"
          lineinfile:
            path: "/etc/letsencrypt/cli.ini"
            line: "webroot-path = /var/www/certbot"
            regexp: "^\\s*#*\\s*webroot-path\\s*=\\s*.*$"
            state: "present"

        - name: "Setup Certbot Service: Create Data Directoriy for Webroot Authenticator"
          file:
            dest: "/var/www/certbot/.well-known/acme-challenge"
            state: "directory"
            owner: "root"
            group: "root"
            mode: "0755"

        - name: "Setup Certbot Service: Install Configuration File for Webroot Authenticator"
          template:
            dest: "/etc/apache2/conf-available/certbot.conf"
            src: "files/etc/apache2/conf-available/certbot.conf.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Setup Apache Service: Enable Modules"
          shell: "a2enmod -q alias"

        - name: "Setup Apache Service: Enable Configurations"
          shell: "a2enconf -q certbot"

        - name: "Setup Certbot Service: Enable Certbot Cron Job"
          service:
            name: "certbot.timer"
            enabled: true


