

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    service_docker_packages:
      - { name: "docker.io" }

  tasks:

    - name: "Setup Docker Service"
      when: "service_docker_enabled|default(false)"
      block:

        - name: "Setup Docker Service: Install Docker Packages"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop: "{{ service_docker_packages|select('distribution', distro, release, attribute='requires')|list }}"

        - name: "Setup Docker Service: Enable Docker Daemon"
          service:
            name: "docker.service"
            enabled: true


