

- hosts: "server"
  become: true
  become_user: "root"

  tasks:

    - name: "Configure Disk Support: Install Tools from Distribution"
      ansible.builtin.dnf:
        name:
          - "hddtemp"
          - "nvme-cli"
          - "smartmontools"
          - "udisks2"
          - "udisks2-iscsi"
          - "udisks2-lsm"
          - "udisks2-lvm2"
        state: "latest"


