

- hosts: "server"
  become: true
  become_user: "root"

  vars:

    software_podman_enabled: true

  tasks:

    - name: "Setup Podman Container Runtime"
      when: "software_podman_enabled|default(false)"
      block:

        - name: "Setup Podman Container Runtime: Install Podman from Distribution"
          ansible.builtin.dnf:
            name:
              - "ansible-collection-containers-podman"
              - "buildah"
              - "podman"
              - "podman-compose"
            state: "latest"

        - name: "Setup Podman Container Runtime: Install Network Manager Configuration File"
          ansible.builtin.template:
            dest: "/etc/NetworkManager/conf.d/podman0.conf"
            src: "{{ playbook_dir }}/files/server/etc/NetworkManager/conf.d/podman0.conf.j2"
            owner: "root"
            group: "root"
            mode: "0644"

        - name: "Setup Podman Container Runtime: Update Avahi Configuration File"
          ansible.builtin.lineinfile:
            path: "/etc/avahi/avahi-daemon.conf"
            create: false
            state: "present"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            backrefs: "{{ item.backrefs }}"
            insertafter: '^\[server\]\s*$'
          loop:
            - regexp: '^[#%].*deny-interfaces\s*=.*$'
              line: 'deny-interfaces=podman0'
              backrefs: true
            - regexp: '^\s*deny-interfaces\s*=\s*$'
              line: 'deny-interfaces=podman0'
              backrefs: true
            - regexp: '^\s*deny-interfaces\s*=\s*((?!(\s*[A-Za-z0-9\-\_]+\s*,)*\s*podman0\s*(,\s*[A-Za-z0-9\-\_]+\s*)*).*)\s*$'
              line: 'deny-interfaces=\1, podman0'
              backrefs: true


