

- hosts: "server"
  become: true
  become_user: "root"

  vars:

    system_sensor_modules:
      - "nct6775"

  tasks:

    - name: "Configuring Hardware Sensors: Install Tools from Distribution"
      ansible.builtin.dnf:
        name: "lm_sensors"
        state: "latest"

    - name: "Configuring Hardware Sensors: Enable Kernel Modules at Boot"
      ansible.builtin.template:
        dest: "/etc/modules-load.d/sensor.conf"
        src: "{{ playbook_dir }}/files/common/etc/modules-load.d/sensor.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"
      when: "system_sensor_modules|default([])|length > 0"


