

- import_playbook: "system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_console_packages:
      - "bchunk"
      - "bsdtar"
      - "cabextract"
      - "ccd2iso"
      - "convmv"
      - "curl"
      - "daa2iso"
      - "ffmpeg"
      - "git"
      - "htop"
      - "innoextract"
      - "mc"
      - "neofetch"
      - "nrg2iso"
      - "nvtop"
      - "openssh"
      - "p7zip"
      - "p7zip-plugins"
      - "rsync"
      - "socat"
      - "sqlite"
      - "sshfs"
      - "telnet"
      - "tmux"
      - "unace"
      - "unrar"
      - "unrar-free"
      - "vim"

  tasks:

    - name: "Setup Console Software"
      when: "software_console_enabled|default(false)"
      block:

        - name: "Setup Console Software: Install Console Software from Distribution"
          ansible.builtin.dnf:
            name: "{{ software_console_packages }}"
            state: "latest"


