

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup SDDM: Install Theme Packages"
      apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: true
        cache_valid_time: 86400
        default_release: "{{ item.release|default(ansible_distribution_release) }}"
      loop:
        - "sddm-theme-debian-breeze"

    - name: "Setup SDDM: Create Configuration Directory"
      file:
        path: "/etc/sddm.conf.d"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Setup SDDM: Update Configuration File"
      template:
        dest: "/etc/sddm.conf.d/theme.conf"
        src: "{{ playbook_dir }}/files/etc/sddm.conf.d/theme.conf.j2"
        owner: "root"
        group: "root"
        mode: "0644"


