

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Enable i386 architecture for x86_64 machines"
      lineinfile:
        path: "/var/lib/dpkg/arch"
        line: "i386"
        state: "present"
      when: "ansible_architecture == 'x86_64'"


