

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Zoom"
      when: "software_zoom_enabled|default(false)"
      block:

        - name: "Setup Zoom: Install Zoom from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/us.zoom.Zoom.flatpakref"
            state: "present"


