

- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_podman_packages:
      - "ansible-collection-containers-podman"
      - "podman"
      - "podman-compose"

  tasks:

    - name: "Setup Podman Container Runtime"
      when: "software_podman_enabled|default(false)"
      block:

        - name: "Setup Podman Container Runtime: Install Podman from Distribution"
          ansible.builtin.dnf:
            name: "{{ software_podman_packages }}"
            state: "latest"


