

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Skype"
      when: "software_skype_enabled|default(false)"
      block:

        - name: "Setup Skype: Install Skype from Flatpak"
          community.general.flatpak:
            name: "https://dl.flathub.org/repo/appstream/com.skype.Client.flatpakref"
            state: "present"


