

- import_playbook: "system.rpmfusion.yml"


- hosts: "all"
  become: true
  become_user: "root"

  vars:

    software_desktop_packages:
      - "@multimedia"
      - "geeqie"
      - "gimp"
      - "intel-media-driver"
      - "keepassxc"
      - "qbittorrent"
      - "skanlite"
      - "vlc"

  tasks:

    - name: "Setup Desktop Software"
      when: "software_desktop_enabled|default(false)"
      block:

        - name: "Setup Desktop Software: Install Desktop Software from Distribution"
          ansible.builtin.dnf:
            name: "{{ software_desktop_packages }}"
            state: "latest"


