

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Enable i386 architecture for x86_64 machines"
      shell: "dpkg --add-architecture i386"
      when: "ansible_architecture == 'x86_64'"


