

- import_playbook: "software.nftables.yml"


- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Firejail"
      when: "software_firejail_enabled|default(false)"
      block:

        - name: "Setup Firejail: Install Software Packages"
          apt:
            name: "{{ item.name }}"
            state: "latest"
            update_cache: true
            cache_valid_time: 86400
            default_release: "{{ item.release|default(ansible_distribution_release) }}"
          loop:
            - { name: "firejail" }
            - { name: "dnsmasq" }

        - name: "Setup Firejail: Enable Networking Options"
          lineinfile:
            path: "/etc/firejail/firejail.config"
            regexp: "#?\\\\s*restricted-network\\\\s+(yes|no)"
            line: "restricted-network no"
            state: "present"

        - name: "Setup Firejail: Install Configuration Files"
          template:
            dest: "{{ item.path }}"
            src: "{{ playbook_dir }}/files/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.mode|default('0644') }}"
          loop:
            - { path: "/etc/dnsmasq.d/firejail.conf" }
            - { path: "/etc/firejail/allow-connection-to-anywhere.inc" }
            - { path: "/etc/firejail/allow-connection-to-anywhere.net" }
            - { path: "/etc/firejail/allow-connection-to-internet.inc" }
            - { path: "/etc/firejail/allow-connection-to-internet.net" }
            - { path: "/etc/firejail/allow-connection-to-lan.inc" }
            - { path: "/etc/firejail/allow-connection-to-lan.net" }
            - { path: "/etc/firejail/allow-fcitx-input.inc" }
            - { path: "/etc/firejail/allow-file-manager-control.inc" }
            - { path: "/etc/firejail/allow-notification.inc" }
            - { path: "/etc/firejail/allow-screensaver-inhibition.inc" }
            - { path: "/etc/firejail/allow-sleep-inhibition.inc" }
            - { path: "/etc/firejail/isolate-networking-with-no-ip.inc" }
            - { path: "/etc/firejail/isolate-networking-with-random-ip.inc" }
            - { path: "/etc/network/interfaces.d/firejail" }
            - { path: "/etc/nftables/firejail.nft" }
            - { path: "/etc/sysctl.d/99-firejail-options.conf" }

        - name: "Setup Guest Service: Enable Dnsmasq Service"
          service:
            name: "dnsmasq.service"
            enabled: true


