

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Website demo.kmchan3.space"
      when: "website_demo_kmchan3_space_enabled|default(false)"
      block:

        - name: "Setup Website demo.kmchan3.space: Create Group"
          group:
            name: "www-demo"
            system: "yes"
            state: "present"

        - name: "Setup Website demo.kmchan3.space: Create User"
          user:
            name: "www-demo"
            group: "www-demo"
            home: "/var/www/demo.kmchan3.space"
            password: "!"
            shell: "/bin/bash"
            create_home: "yes"
            move_home: "no"
            system: "yes"
            state: "present"

        - name: "Setup Website demo.kmchan3.space: Create Directories"
          file:
            dest: "{{ item.name }}"
            state: "directory"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.mode|default('0755') }}"
          loop:
            - { name: "/var/log/websites", owner: "root", group: "root", mode: "0755" }
            - { name: "/var/log/websites/demo.kmchan3.space", owner: "www-demo", group: "www-demo", mode: "0750" }
            - { name: "/var/www/demo.kmchan3.space", owner: "www-demo", group: "www-demo", mode: "0755" }
            - { name: "/var/www/demo.kmchan3.space/html", owner: "www-demo", group: "www-data", mode: "0755" }
            - { name: "/var/www/demo.kmchan3.space/html/.well-known", owner: "www-demo", group: "www-data", mode: "0755" }
            - { name: "/var/www/demo.kmchan3.space/projects", owner: "www-demo", group: "www-demo", mode: "0755" }

        - name: "Setup Website demo.kmchan3.space: Install Configuration Files"
          template:
            dest: "{{ item.path }}"
            src: "files/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.mode|default('0644') }}"
          loop:
            - { path: "/etc/apache2/sites-available/local_demo.kmchan3.space.conf" }
            - { path: "/etc/logrotate.d/demo.kmchan3.space" }
            - { path: "/etc/sudoers.d/demo.kmchan3.space", mode: "0600" }
            - { path: "{{ php_config_path }}/fpm/pool.d/demo.kmchan3.space.conf" }

        - name: "Setup Website demo.kmchan3.space: Enable Custom Apache Configuration"
          file:
            dest: "/etc/apache2/{{ item.type }}-enabled/{{ item.name }}"
            src: "/etc/apache2/{{ item.type }}-available/{{ item.name }}"
            state: "{{ item.state|default('link') }}"
          loop:
            - { type: "sites", name: "local_demo.kmchan3.space.conf", state: "link" }


