

- hosts: "all"
  become: true
  become_user: "root"

  tasks:

    - name: "Setup Website desktop.kmchan3.space"
      when: "website_test_kmchan3_space_enabled|default(false)"
      block:

        - name: "Setup Website desktop.kmchan3.space: Install Configuration Files"
          template:
            dest: "{{ item.path }}"
            src: "files/{{ item.path }}.j2"
            owner: "{{ item.owner|default('root') }}"
            group: "{{ item.group|default('root') }}"
            mode: "{{ item.group|default('0644') }}"
          loop:
            - { path: "/etc/apache2/sites-available/000-desktop.kmchan3.space.conf" }

        - name: "Setup Website desktop.kmchan3.space: Enable Custom Apache Configuration"
          file:
            dest: "/etc/apache2/{{ item.type }}-enabled/{{ item.name }}"
            src: "/etc/apache2/{{ item.type }}-available/{{ item.name }}"
            state: "{{ item.state|default('link') }}"
          loop:
            - { type: "sites", name: "000-desktop.kmchan3.space.conf", state: "link" }


