#!/bin/bash

set -e

ARCH="x86_64"
LANG="en-US"
ROOT="/usr/local/lib/firefox"

PRODUCT=$(curl -sfI 'https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US' | grep -o 'firefox-[0-9.]\+[0-9]')

if [[ "x${PRODUCT}" == "x" ]]; then
  echo "Current version of firefox cannot be determined"
else
  VERSION="${PRODUCT:8}"
  echo "The latest version of firefox is ${VERSION}"

  DIRECTORY="firefox-${VERSION}"
  ARCHIVE="firefox-${VERSION}.tar.bz2"
  URLBASE="https://ftp.mozilla.org/pub/firefox/releases/${VERSION}"
  URLEXT="linux-${ARCH}/${LANG}/${ARCHIVE}"
  CHECKSUM=$(curl -s "${URLBASE}/SHA256SUMS" | grep -F "${URLEXT}" | cut -d ' ' -f 1)

  if [[ -f "${ROOT}/${DIRECTORY}/${ARCHIVE}" ]]; then
    echo "Package file for firefox ${VERSION} is already downloaded"
  else
    mkdir -p "${ROOT}/${DIRECTORY}"
    cd "${ROOT}/${DIRECTORY}"

    echo "Downloading package file for firefox ${VERSION}..."
    curl -s -o "${ARCHIVE}.incoming" "${URLBASE}/${URLEXT}"

    echo "Validating package file..."
    echo "${CHECKSUM} ${ARCHIVE}.incoming" | sha256sum -c --status

    echo "Saving package file..."
    mv "${ARCHIVE}.incoming" "${ARCHIVE}"
  fi

  if [[ -f "${ROOT}/${DIRECTORY}/firefox" ]]; then
    echo "Package file for firefox ${VERSION} is already extracted"
  else
    cd "${ROOT}/${DIRECTORY}"

    echo "Extracting package file..."
    tar --strip-components=1 -xf "${ROOT}/${DIRECTORY}/${ARCHIVE}"
    ln -sf "${ROOT}/${DIRECTORY}/firefox" "/usr/local/bin/firefox"
  fi
fi


